### ISSUE TITLE
Add an option to turn off entry alignment

### ISSUE THREAD

**Issue by draivin** [tamasfe/taplo#10]
It is often undesirable to align on items as shown on the following image, it would be nice to be able to format with one whitespace around the equals sign.

![image](https://user-images.githubusercontent.com/947593/84582969-79b29580-adc9-11ea-9081-1c661f1db7f7.png)

**Comment by tamasfe** [comment]
Thanks, I will add an option for this in the next version. The question is, should alignment be enabled by default?

**Comment by draivin** [comment]
Just my own view, but as a user I expected it to default to unaligned items, the same as `rustfmt` which has the options `struct_field_align_threshold` and `enum_discrim_align_threshold` set as 0 by default.

**Comment by tamasfe** [comment]
Version 0.5.0 of the extension now has this option as `evenBetterToml.formatter.alignEntries`.

In the end I decided to keep it enabled as default in order not to surprise users that expect the current behaviour.
