### ISSUE TITLE
Add VSCode configuration option to disable formatting completely

### ISSUE THREAD

**Issue by chdsbd** [tamasfe/taplo#100]
Thanks for this extension. The auto complete is great!

It would be useful for me if there was an option to disable formatting completely.

**Comment by tamasfe** [comment]
I'm glad you find it useful!

Could you expand more on the issue a bit? The extension uses the standard LSP API for formatting, so it doesn't format anything unless you configure vscode to do so.

**Comment by chdsbd** [comment]
You're right, it's a VSCode thing I needed to change.

I added the following to my settings json file and formatting is disabled.

```json
{
  "[toml]": {
    "editor.formatOnSave": false
  }
}
```

Thanks
