### ISSUE TITLE
does the js lib support m1?

### ISSUE THREAD

**Issue by GopherJ** [tamasfe/taplo#101]
Hi, I enjoy taplo for a while and recently I switched to macbook pro m1 and found it stopped working with node@12.20.1

do you have an idea on this?

**Comment by GopherJ** [comment]
I'm using coc-toml btw.

**Comment by tamasfe** [comment]
Hi, unfortunately I have no access to macs, so I cannot investigate this one.

You could try to see if the cli works via either `cargo install taplo-cli && taplo help` and `npx @taplo/cli help`.

**Comment by GopherJ** [comment]
@tamasfe

**Comment by tamasfe** [comment]
Thanks, seems like a [node issue](https://stackoverflow.com/questions/65856300/wasm-code-commit-allocation-failed-process-out-of-memory) on the arm macs.

**Comment by GopherJ** [comment]
@tamasfe tested works using node@15.14.0, I'll wait the next LTS before switching to it, thanks!
