### ISSUE TITLE
Support markdown frontmatter

### ISSUE THREAD

**Issue by jplatte** [tamasfe/taplo#104]
One thing the "Better TOML" VSCode extension does but yours doesn't is highlight frontmatter. I'm not sure whether this should be applied to more formats than markdown, but there it's definitely common.

TOML frontmatter uses `+++` delimiters and is supported in a few different static site engines ([Hugo](https://gohugo.io/content-management/front-matter/#front-matter-formats), [Zola](https://www.getzola.org/documentation/content/page/#front-matter), probably others).

**Comment by tamasfe** [comment]
Frontmatter and TOML code block syntax highlights are now supported in markdown in the latest extension.
