### ISSUE TITLE
VS can not handle relative paths on Windows

### ISSUE THREAD

**Issue by K0GiHF9S** [tamasfe/taplo#112]
as is:
---

On Windows, if "evenBetterToml.taploConfig" or "evenBetterToml.schema.associations" is set with relative path, conversion to absolute path is fails.

to be:
---

You can specify file specification with relative paths on Windows.

environment:
---

Windows 10
VS 1.56.2
ext. 0.12.1

to reproduce:
---

File configuration for verification.

- c:\test\.vscode\setting.json
- c:\test\test.toml
- c:\test\scheme_test.json

Contents of setting.json

```json
{
    "evenBetterToml.taploConfig": "taplo.toml",
    "evenBetterToml.schema.associations": {
        "^(.*(/|\\\\)test\\.toml|test\\.toml)$": "scheme_test.json",
    },
}
```

It is a LSP log when I edited test.toml.

```log
failed to load configuration file: JsValue(Error: ENOENT: no such file or directory, open 'c:\c%3A\test\taplo.toml'
Error: ENOENT: no such file or directory, open 'c:\c%3A\test\taplo.toml')
failed to save schema index: JsValue(Error: ENOENT: no such file or directory, mkdir '/E:/Users/UserName/AppData/Roaming/Code/User/globalStorage/tamasfe.even-better-toml'
Error: ENOENT: no such file or directory, mkdir '/E:/Users/UserName/AppData/Roaming/Code/User/globalStorage/tamasfe.even-better-toml'
    at mkdirSync (fs.js:987:3)
    at Object.e.mkdirSync (electron/js2c/asar_bundle.js:5:11962)
    at mkdir (e:\Users\UserName\.vscode\extensions\tamasfe.even-better-toml-0.12.1\dist\server.js:72:31)
    at e:\Users\UserName\.vscode\extensions\tamasfe.even-better-toml-0.12.1\dist\index-0a0a4622.js:49:3414
    at e:\Users\UserName\.vscode\extensions\tamasfe.even-better-toml-0.12.1\dist\index-0a0a4622.js:49:1983
    at <anonymous>:wasm-function[1769]:0x3676fb
    at <anonymous>:wasm-function[105]:0xc89e2
    at <anonymous>:wasm-function[3160]:0x396f8f
    at <anonymous>:wasm-function[1368]:0x33fdfd
    at wasm_bindgen__convert__closures__invoke1_mut__h99d496d9e9b3b669 (<anonymous>:wasm-function[2984]:0x395ff6))
failed to load schema (scheme_test.json): JsValue(Error: ENOENT: no such file or directory, open 'c:\c%3A\test\scheme_test.json'
Error: ENOENT: no such file or directory, open 'c:\c%3A\test\scheme_test.json')
failed to load schema: JsValue(Error: ENOENT: no such file or directory, open 'c:\c%3A\test\scheme_test.json'
Error: ENOENT: no such file or directory, open 'c:\c%3A\test\scheme_test.json')
```

due to:
---

In "taplo-lsp", the file scheme is converted to the path with `Url.path` method.But this is only in UNIX environments that are not URL encoded.
ex: *file:///c%3A/test/test.toml* => */c%3A/test/test.toml*
There are also `url.to_file_path` methods, but this is not provided by WASM.

suggestion:
---

How about passing parameters passing to the LSP wrapper as the file scheme instead of the file path?

**Comment by tamasfe** [comment]
Thanks for the detailed report!

> How about passing parameters passing to the LSP wrapper as the file scheme instead of the file path?

I'm not sure what you mean _exactly_. Passing the entire URI to the `readFile` of the wrapper regardless of scheme would mean that the wrapper would be responsible for retrieving files no matter what. The wrapper is only there for things the LSP cannot do alone (due to the WASM context), and I would not move logic outside of it if possible.

The wrapper provides an `isWindows` method for quirks like this one. It could be used to handle paths differently inside the LSP.
