### ISSUE TITLE
Corrupt ZIP

### ISSUE THREAD

**Issue by cryptoquick** [tamasfe/taplo#113]
After finding this in the VS Code store and clicking install, I was notified of this error in the log:

`[2021-05-15 23:17:45.368] [renderer3] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at H.downloadInstallableExtension (file:///usr/lib/code/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///usr/lib/code/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]`

OS: Arch Linux
VS Code: 1.55.2

I was able to solve it by following the prompts to download the VSIX file and install it manually. Still, not an ideal user experience. I hope this helps others.

**Comment by tamasfe** [comment]
I don't think this is an extension-specific issue as it is packaged by [vsce](https://github.com/microsoft/vscode-vsce) and requires nothing else.

**Comment by NightlyHerb** [comment]
That doesn't happen to me:
`[2021-05-21 12:09:53.423] [sharedprocess] [info] Extensions installed successfully: tamasfe.even-better-toml`
With the following setup (Help>About>[Copy])
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by tamasfe** [comment]
I'll close this as this doesn't seem to be a problem with taplo, feel free to create a new issue otherwise.
