### ISSUE TITLE
workspace-relative paths only work in the first workspace folder

### ISSUE THREAD

**Issue by Profpatsch** [tamasfe/taplo#118]
When I have a vscode project with multiple folders in the workspace, like

```
project1/
  foo.toml
project2/
  bar.toml
```

the lsp mode will set up the `project1` as the workspace directory on initialize:

https://github.com/tamasfe/taplo/blob/5681a56ac51c4b518f1131a43ec2c6fba893bf5c/taplo-lsp/src/handlers.rs#L39-L50

and then never change it.

So if `bar.toml` contains a relative schema header like

```
#:schema ./bar-schema.json
```

the lsp mode will try to resolve it to

```
project1/bar-schema.json
```

instead of 

```
project2/bar-schema.json
```

**Comment by Profpatsch** [comment]
The server would have to use [`workspace_folders`](https://docs.rs/lsp-types/0.89.1/lsp_types/struct.InitializeParams.html) instead.

But honestly, I don’t see why the relative paths can’t be relative to the file itself. That would make discoverability a lot easier, given that you can just “jump to file” in your editor that way.

**Comment by tamasfe** [comment]
Thank you, the comment-based schemas were hacked together due to a use-case in #95 and they simply use the same workspace resolution for this reason, indeed file-relative paths would probably make more sense for them.

**Comment by Profpatsch** [comment]
I got the rust project to build locally, I might take a look today.

**Comment by Profpatsch** [comment]
Okay, I got the rust build to work via

```cd js/vscode; yarn build````

but I’m unsure how I can get the vscode extension to pick up the wasm code that I compiled in that step.

So I’m kinda stuck.

**Comment by Profpatsch** [comment]
nvm, should have read the https://github.com/tamasfe/taplo/blob/master/CONTRIBUTING.md

https://github.com/tamasfe/taplo/blob/master/scripts/vscode-build-ext.sh did the trick

**Comment by tamasfe** [comment]
One thing missing from the `CONTRIBUTING.md` is that you have to build the `js/lsp` as well and [`yarn link`](https://classic.yarnpkg.com/en/docs/cli/link/) it in `js/vscode` otherwise the extension will use the lsp from npm.
