### ISSUE TITLE
Rework formatting

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#123]
The current formatting code is a huge blob of spaghetti with barely any structure and full of hacks.

Things to consider:
- make it more modular
- drop building green trees and work with strings only
- write more tests to make sure nothing breaks compared to the current behaviour

**Comment by tamasfe** [comment]
This is mostly done, new formatter options are yet to be documented on the website.

**Comment by gilescope** [comment]
People are asking me on the formatting front if it's possible to not linebreak if there's just one item in the list.

E.g. stick with this:
`sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", features = ["std"]  }`
rather than what currently happens:
```
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", features = [
    "std",
]  }
```

**Comment by gilescope** [comment]
Ah it was hitting the line width. Thank you so much for this crate!
