### ISSUE TITLE
Wrong Indent Size

### ISSUE THREAD

**Issue by AurevoirXavier** [tamasfe/taplo#126]
Please check the longest line

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/16152305/122711187-551eb280-d294-11eb-98ed-441b4dc17e76.png">

**Comment by tamasfe** [comment]
Vertical alignment was broken in the latest release, if you had no other formatting issues before, please revert the extension to the previous version (`0.12.2`) until #123 is resolved.

**Comment by tamasfe** [comment]
This should be fixed in taplo `0.6.1`, and vscode extension version `0.13.1`.
