### ISSUE TITLE
Option to indent keys under table

### ISSUE THREAD

**Issue by DAmNRelentless** [tamasfe/taplo#127]
It would be nice to have an option that keys below a table are indented.

Right now, my TOML looks like this:
![](https://i.imgur.com/VcgM075.png)
And when formatted, it looks like this:
![](https://i.imgur.com/CXa3vhM.png)

I want to keep the indents though. In my opinion it makes it much more readable.
I know the typical TOML format doesn't have indents either but it would be nice to have a configurable option for this.

**Comment by tamasfe** [comment]
This should be available in tablo `0.6.1` and the vscode extension version `0.13.1`.

**Comment by Stanzilla** [comment]
As "Even Better Toml › Formatter: Indent Entries". works well, thank you!

**Comment by JugglerX** [comment]
I also prefer the indents.

I used the following vscode settings in my `.vscode/settings.json` to achieve the same look as the OP screenshot.

```
{
  "[toml]": {
    "editor.defaultFormatter": "tamasfe.even-better-toml",
    "editor.tabSize": 2,
    "editor.formatOnSave": true
  },
  "evenBetterToml.formatter.indentTables": true,
  "evenBetterToml.formatter.indentEntries": true,
  "evenBetterToml.formatter.compactEntries": false
}
```
