### ISSUE TITLE
Support schemas contributed by other Vscode extensions

### ISSUE THREAD

**Issue by OrangeUtan** [tamasfe/taplo#130]
The Yaml extension from Readhat supports schemas that are contributed by other extensions (https://github.com/redhat-developer/vscode-yaml#mapping-a-schema-in-an-extension).

Other extensions just have to specify which schemas they are contributing:
```
{
  "contributes": {
    "yamlValidation": [
      {
        "fileMatch": "yourfile.yml",
        "url": "./schema.json"
      }
    ]
  }
}
```

Adding this feature would allow extensions that support multiple file types to easily use the same schemas for Json, Yaml and Toml without the need for a registry.

An example of how the feature could look like:
```
{
  "contributes": {
    "tomlValidation": [
      {
        "fileMatch": "yourfile.toml",
        "url": "./schema.json"
      }
    ]
  }
}
```

**Comment by tamasfe** [comment]
This looks like an awesome idea.

Do LSPs receive thse contributions, or is this a vscode-only thing? If it's the latter, we need to figure out how to merge these with the rules in the configuration and pass them to the language server as well.

**Comment by OrangeUtan** [comment]
The redhat extension has a somewhat similar system to this one, as it supports associating files with schemas in the workspace settings. Contributed schemas seem to be treated much the same way. They are collect by analyzing the 'package.json' of all extensions:  https://github.com/redhat-developer/vscode-yaml/blob/5647b422b86cc2e67a8949ee7eb7f8ab6d5f1089/src/extension.ts#L207.

```
vscode.extensions.all.forEach(e =>
    const contributed schemas = e.packageJson.contributes.yamlValidation
)
```

**Comment by OrangeUtan** [comment]
They then send these associations to the LanguageClient: https://github.com/redhat-developer/vscode-yaml/blob/5647b422b86cc2e67a8949ee7eb7f8ab6d5f1089/src/extension.ts#L146

So, to try to answer your question: The Language Server receives these contributions by manually doing so.

**Comment by tamasfe** [comment]
It's been quite a while, sorry, but this is now supported. ([docs](https://taplo.tamasfe.dev/configuration/developing-schemas.html#visual-studio-code-extensions))
