### ISSUE TITLE
Depend on rowan release candidate?

### ISSUE THREAD

**Issue by thomaseizinger** [tamasfe/taplo#147]
Rowan has had several RC for the 0.13 release: https://github.com/rust-analyzer/rowan/releases

These releases introduce a mutation-based API that makes it much easier to modify the AST. I am [using this feature](https://github.com/dprint/dprint-plugin-toml/pull/1) for formatting `Cargo.toml` files using the `dprint-toml-plugin`.

To do that, I am depending on a fork to swap out the dependency for the rowan RC. The [changes](https://github.com/thomaseizinger/taplo/commit/68d8e321a03c2cdc56e26fb6fe4fa7814e902fd5) to make this work are minimal.

Would you be okay in depending on the RC in here and releasing a new version? I've also [asked](https://github.com/rust-analyzer/rowan/issues/110) about a 0.13 release but I am not sure when that would happen!

**Comment by tamasfe** [comment]
I'm definitely open to this, as I've been planning on making a rewrite feature, it should be a lot easier with rowan supporting it directly.

**Comment by thomaseizinger** [comment]
> I'm definitely open to this, as I've been planning on making a rewrite feature, it should be a lot easier with rowan supporting it directly.

Sweet, that is good news!

It is not a huge blocker for https://github.com/dprint/dprint-plugin-toml at the moment because the WASM binary releases can be made without publishing to crates.io. However, the primary maintainer would like to eventually publish to crates.io to allow use of the plugin in other usecases.

Let's see if the RA folks come back with a timeline on the 0.13 release.

**Comment by thomaseizinger** [comment]
Version 0.14.1 has been released: https://docs.rs/rowan/0.14.1/rowan/
