### ISSUE TITLE
Comment puzzle

### ISSUE THREAD

**Issue by gilescope** [tamasfe/taplo#157]
In the online editor the comment gets preserved:
```
runtime-benchmarks = [
  # a comment
]
```
but master cli doesn't preserve it with default config:
```
runtime-benchmarks = []
```

Any ideas?

**Comment by tamasfe** [comment]
Looks like I forgot to deploy a new version of the site with the latest releases.

This seems to be a bug in the new formatter though.

**Comment by gilescope** [comment]
If there's an element before the comment or after it seems to keep the comment so it's just if there's no elements in the array.
I'm blown away by the `align_entries = true` btw - it makes such a difference to readability. This is all so much good work that you've done.

**Comment by tamasfe** [comment]
Thanks, I'm glad you find it useful!
