### ISSUE TITLE
jsonrpc request to the lsp server timed out

### ISSUE THREAD

**Issue by buzztaiki** [tamasfe/taplo#162]
I'm currently trying to build an lsp client for [emacs-lsp](https://github.com/emacs-lsp/lsp-mode).

When I connect to a server started by `taplo-lsp run` from a client and send an `initialize` message, it seems to time out without returning a response.

I checked taplo-lsp and found that it is waiting for the following `read_exact`:

https://github.com/tamasfe/taplo/blob/6a2208603af9df49b6ea699f55bc94f926c0a116/taplo-lsp/bin/lsp/stdio.rs#L165

Also, I removed the following `+ 2` and it works fine:

https://github.com/tamasfe/taplo/blob/6a2208603af9df49b6ea699f55bc94f926c0a116/taplo-lsp/bin/lsp/stdio.rs#L153

This problem was also reproduced by the following code.

```ts
import * as cp from 'child_process';
import * as rpc from 'vscode-jsonrpc/node';

type Req = {
  woo: string
}

async function main() {
  let childProcess = cp.spawn(process.env["TAPLO_LSP"] ?? "taplo-lsp", ["run"]);

  let connection = rpc.createMessageConnection(
    new rpc.StreamMessageReader(childProcess.stdout),
    new rpc.StreamMessageWriter(childProcess.stdin));
  
  connection.listen();
  let request = new rpc.RequestType<Req, any, any>("initialize");
  // expect Invalid params error
  console.log(await connection.sendRequest(request, { woo: "moo"}));
}


(async function() {
  await main();
})()
```

**Comment by buzztaiki** [comment]
I found a similar code in tcp.rs:

https://github.com/tamasfe/taplo/blob/6a2208603af9df49b6ea699f55bc94f926c0a116/taplo-lsp/bin/lsp/tcp.rs#L211


Also, lsp-server of rust-analyzer did not adjust a size of Content-Length.

https://github.com/rust-analyzer/lsp-server/blob/4896c0ad938ac581c6cc2ec50b8bad0b35a076be/src/msg.rs#L254-L256
```rust
        if header_name == "Content-Length" {
            size = Some(header_value.parse::<usize>().map_err(invalid_data)?);
        }
```

**Comment by tamasfe** [comment]
That seems like a bug, the content-length should already include the `\r\n` indeed.

Unfortunately I don't have any time for open source right now, so any PR is welcome.

**Comment by buzztaiki** [comment]
I've create PR #163

**Comment by tamasfe** [comment]
Thanks! 0.2.5 of `taplo-lsp` should be published soon with it.
