### ISSUE TITLE
Changes to taplo-lsp are not checked into this repo?

### ISSUE THREAD

**Issue by polyzen** [tamasfe/taplo#165]
The latest code for taplo-lsp in this repo appears to be from 0.2.1. A couple differences I noticed are that the crate for `0.2.5` has the proper version in its `Cargo.toml` and it also has a `Cargo.lock` available.

**Comment by tamasfe** [comment]
The published version is based on tags (e.g. https://github.com/tamasfe/taplo/tree/release-lsp-0.2.5), and the version in `Cargo.toml` is replaced during CD.

I believe `Cargo.lock` is generated by cargo because the crate contains an executable target.

**Comment by polyzen** [comment]
Thanks for clearing that up!
