### ISSUE TITLE
[lsp] Add support for didChangeConfiguration

### ISSUE THREAD

**Issue by kkiyama117** [tamasfe/taplo#167]
When using `taplo-lsp` as a client application and when lsp client notifies `workspace/configuration`,  the configuration state in taplo-lsp always turns out to be None. I tried to implement to get values like [this](https://github.com/kkiyama117/taplo/commit/a8adc704238d2a7b0f3521254e1f929e4efbc01f), and it works, but I'm not sure that this implementation is correct and not bad for the evenBetterToml (vscode) version, so I'd like to hear your opinion.

**Comment by tamasfe** [comment]
What is the goal exactly?

**Comment by kkiyama117** [comment]
I want to use taplo with [`vim-lsp`](https://github.com/mattn/vim-lsp-settings/blob/master/settings/taplo-lsp.vim), but when it calls `workspace/didChangeConfiguration`, config in `WorldState` always be `None` and no semantics and format option works.

**Comment by tamasfe** [comment]
Sorry it took me a while to understand the issue. When I implemented configuration I made sure that it worked correctly with an explicit call to the client, no matter what chenged. I didn't know what is given in the `didChangeConfiguration` parameters (and in fact I still don't).

Feel free to submit a PR if your implementation works. If it's always the whole configuration object and we don't have to do any merging with the existing configuration, it should work just fine.

**Comment by timbedard** [comment]
It says "the actual changed settings" in [the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workspace_didChangeConfiguration), but at least in nvim-lspconfig they're just passing the whole settings object. 🤷

> I'd like to use taplo with naming as `taplo` or `taplo-lsp` if I can.

This would be nice. We could check for `taplo`/`taplo-lsp` first and then check for `evenBetterToml` if it's not found.

I haven't been able to get it working with Neovim/nvim-lspconfig yet even with @kkiyama117's fix though. 😕

**Comment by kkiyama117** [comment]
With the changes to vim-lsp, everything now works fine even if I'm using the current version.

**Comment by kkiyama117** [comment]
@timbedard [This](https://github.com/mattn/vim-lsp-settings/blob/master/settings/taplo-lsp.vim) is the setting taplo works with vim-lsp. I'm not familiar with Lua and `nvim-lspconfig`, but it might help you.

**Comment by timbedard** [comment]
Huh. yeah, I'm doing something similar:
```lua
require("lspconfig").taplo.setup({
  settings = {
    evenBetterToml = {
      formatter = {
        alignEntries = true,
        indentTables = true,
        reorderKeys = true,
      },
    },
  },
})
```

 I'll have a look into how vim-lsp is written. Maybe there's something missing in nvim-lspconfig (or Neovim's client) in terms of responding to the `workspace/configuration` request.

**Comment by tamasfe** [comment]
> It says "the actual changed settings" in the spec

Thanks, that's unfortunate, some merging logic/macro will have to be used then for this to work according to the spec.

> We could check for taplo/taplo-lsp first and then check for evenBetterToml if it's not found.

Right now `evenBetterToml` section is baked in the LSP library because it was easier at the beginning. I'm definitely open to changing this, as far as I remember the client should be able to configure it at initialization.

**Comment by timbedard** [comment]
Okay, so I have it working by sending:
```lua
  settings = {
    evenBetterToml = {
      schema = {
        enabled = true,
        repositoryEnabled = true,
        repositoryUrl = "https://taplo.tamasfe.dev/schema_index.json",
      },
      cachePath = vim.fn.stdpath("cache") .. "/taplo",
      formatter = { indentTables = true },
    },
  }
```

However,

1. _None_ of it works if the `formatter` key is omitted or empty. 🤷
2. `settings.evenBetterToml.cachePath` doesn't seem to work.
