### ISSUE TITLE
[vscode] Respect the VS Code settings editor.formatOnSave

### ISSUE THREAD

**Issue by Karl255** [tamasfe/taplo#169]
The extension ignores the value of the `editor.formatOnSave` setting, it instead always formats the file no matter what. There's probably some other standards VS Code settings that this extension ignores as well - like way too many VS Code extensions do.

**Comment by tamasfe** [comment]
> The extension ignores the value of the `editor.formatOnSave` setting,

The extension doesn't do any formatting by itself and only provides a formatter service for VS Code. My first guess would be an another extension or a workspace setting override.

> There's probably some other standards VS Code settings that this extension ignores as well

Feel free to open issues for them.

**Comment by gilescope** [comment]
Tangential but the "Formatting Toggle" extension is great if you need to turn on and off format on save all the time.
