### ISSUE TITLE
Bug: Schema Directive not respected

### ISSUE THREAD

**Issue by pengolod** [tamasfe/taplo#174]
I have a toml file `pack.toml`:

```toml
#:schema = https://rawcdn.githack.com/comp500/packwiz-spec/09ada88785e56c969e8920a8deeea1d4dc132ded/schemas/pack.json

name = "Pengolod's Base Modpack"
author = "Pengolod"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9347416c7ae9bc5df9ac5fd093dcf3a6aeea73aea7fc61de297504e0d37c2309"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
acceptable-game-versions = ["1.17"]
```

and I ran `npx @taplo/cli lint pack.toml` and it passed:

```sh
➜  npx @taplo/cli lint pack.toml
success: processed 1 document with no errors 
```

but with `npx @taplo/cli lint --schema 'https://rawcdn.githack.com/comp500/packwiz-spec/09ada88785e56c969e8920a8deeea1d4dc132ded/schemas/pack.json' pack.toml` it failed correctly, as the above file is a non-valid config.

```sh
➜  npx @taplo/cli lint --schema 'https://rawcdn.githack.com/comp500/packwiz-spec/09ada88785e56c969e8920a8deeea1d4dc132ded/schemas/pack.json' pack.toml
error: failed schema validation
  --> pack.toml:15:28
   | 
15 | acceptable-game-versions = ["1.17"]
   |                            ^^^^^^^^ invalid type, expected "String", not "Array"
failure: processed 1 document with 1 error 
```

https://raw.githack.com/ is a lazy cdn for context - i can confirm the link works!

**Comment by tamasfe** [comment]
The schema directive is undocumented for a reason, it's not yet finished and only the LSP uses it.

It was unclear whether it would stay as is (#97), but now I'm leaning towards stabilizing it, so PRs are welcome!
