### ISSUE TITLE
Behavior when `schema.enabled` key is omitted

### ISSUE THREAD

**Issue by hituzi-no-sippo** [tamasfe/taplo#176]
Taplo CLI version is `Taplo TOML Utility 0.4.1 (x86_64-unknown-linux-gnu)`.

According to the following document, if omit the `enabled` key, the behavior is the same as `enabled = true`.

https://github.com/tamasfe/taplo/blob/786456382379ebe7a64d6ff9d4dd4710e3e53e06/site/src/pages/configuration.mdx#L85-L90

However, when I actually check behavior, it seems to behave the same as `enabled = false` as follows.

Is the documentation incorrect?

## omit `schema.enabled`

```shell
$ cat taplo.toml
[schema]
path = "taplo://taplo.toml"
$ taplo lint validator_test.toml
success: processed 1 document with no errors
```

## `schema.enabled = true`

```shell
$ cat taplo.toml
[schema]
path = "taplo://taplo.toml"
enabled = true
$ taplo lint validator_test.toml
error: failed schema validation
 --> validator_test.toml:1:1
  |
1 | invalid_key = true
  | ^^^^^^^^^^^^ unknown property
failure: processed 1 document with 1 error
````

## `schema.enabled = false`

```shell
$ cat taplo.toml
[schema]
path = "taplo://taplo.toml"
enabled = false
$ taplo lint validator_test.toml
success: processed 1 document with no errors
```

I think the following code is related to this issue.

https://github.com/tamasfe/taplo/blob/fb40b1c8c752df21cb6486ec27636a74920c2365/taplo-cli/src/config.rs#L64

**Comment by tamasfe** [comment]
Thanks, yes, it's a bug.
