### ISSUE TITLE
Schemas not working?

### ISSUE THREAD

**Issue by Aloso** [tamasfe/taplo#181]
I noticed that the `Cargo.toml` schema hasn't been working for a while. When I hover a key, no tooltip appears, and I get no useful autocompletion.

I tried out various things: I restarted the extension, I created a `evenBetterToml.schema.associations` setting and a `.taplo.toml` file in the workspace that includes the `Cargo.toml` file. I added the schema `taplo://cargo.toml` (I also tried `https://taplo.tamasfe.dev/schemas/cargo.toml.json` and a local copy with `file://`). Nothing works.

System information:
* Editor: VS Code OSS 1.58.0
* Extension: Even Better Toml 0.14.2
* OS: Manjaro Linux
* Desktop: KDE 5.86.0 / Plasma 5.22.5

**Comment by tamasfe** [comment]
Oh. Yet another [letsencrypt certificate issue](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/). I haven't noticed it as I already have the schemas downloaded.

This is hopefully fixed by updating dependencies (as it seems to be unrelated to nodejs versions). However all releases right now are blocked as I haven't got to figuring out what is going on in #175.

**Comment by Aloso** [comment]
It's working! Thanks for helping, and of course for developing this great plugin 😀

**Comment by syphar** [comment]
@tamasfe first of all, thank you for building this! 

I added `taplo-lsp` to nvim setup, and while syntax errors are shown in diagnostics, schema errors aren't. 

Is this still this SSL issue? I tried to make it work with the [setting changes above and local schemas](https://github.com/tamasfe/taplo/issues/181#issuecomment-940182882), but I didn't see diagnostic errors. 

The `taplo` CLI shows errors correctly when called with `-S`. 

How could I debug this? I'm happy to dig into also providing a fix if this is a bug. I probably would need pointers to where to look. 

- `taplo --version` => `0.4.1`, 
- `taplo-lsp --version` => `0.2.6`

both installed via `cargo install`

**Comment by Aloso** [comment]
@syphar taplo doesn't report schema errors AFAIK, it only provides completions, documentation tooltips and so on.

**Comment by syphar** [comment]
Thank you for the quick response! 

You mean the lsp does not report? or also the CLI? 

Completions I don't see either  :)

But isn't this here Schema validation? 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/540890/144273139-4a1cd758-28de-4f6f-8409-92128777b7da.png">

**Comment by Aloso** [comment]
I didn't know taplo reports errors. I only use the LSP (with the `Even Better Toml` vs code extension), which doesn't report errors, at least for me.

**Comment by syphar** [comment]
The LS also does report format errors like missing `]` correctly, only the schema errors are missing for me.

**Comment by Aloso** [comment]
Yes, that's what I meant.

**Comment by syphar** [comment]
If this is a gap in the LS implementation I would probably even be willing to see if I can contribute this

**Comment by syphar** [comment]
> Schema errors should be reported by the LSP as well. As far as I know nvim taplo relies on the WASM LSP npm builds (I'm not certain, as it is not maintained by me), so yes, it is likely still an SSL issue as I haven't been able to publish a new release (_npm publish started returning 404 for whatever reason and I gave up there for now_).
> 

The neovim config [is just using `cargo install taplo-lsp`](https://github.com/neovim/nvim-lspconfig/blob/5b8624c1bcd332e9fd7ae33a2ca910adb31a7ae7/doc/server_configurations.md#taplo), does this make a difference related to the behavior? 
Also to my autocomplete not working? (other LSP work just fine)

> So there is nothing you can do I'm afraid as this is a publishing issue that awaits me. I'm overwhelmed with university+work right now so I can barely find the time, sorry about the inconvenience.
> 
I'm sorry to hear that, I'm happy to help if there is anything. 

> > I didn't know taplo reports errors. I only use the LSP (with the Even Better Toml vs code extension), which doesn't report errors, at least for me.
> 
> That's weird, it does for me, should be a separate issue then.
> 
> ![image](https://user-images.githubusercontent.com/25967296/144274382-70dbcbb8-32ea-4853-8080-dbd3dc3ac52c.png)
> 
> If you're getting completions but not schema errors, then it's a bug.

**Comment by syphar** [comment]
short process update:
I start seeing schema errors in neovim when I manually inject the following configuration in `taplo-lsp::handlers::initialize`: 
```rust
    w.configuration = Configuration {
        schema: SchemaConfiguration {
            enabled: Some(true),
            repository_enabled: Some(true),
            repository_url: Some(String::from("taplo://taplo.toml")),
            ..Default::default()
        },
        ..Default::default()
    };
```

I'm still digging further, but it looks like this is either a problem with the lsp server not reading the global config in `~/taplo.toml` (should it? ) or the `settings` I pass to `require("lspconfig").taplo.setup({})` does not end up in `initialize`. 

I don't see any SSL error when directly using the lsp binary. 

I'll dig further, but I would be quicker with hints by @tamasfe

**Comment by syphar** [comment]
So, part of the confusion came from me not knowing the difference between `settings` and `init_options` (e.g. `workspace/configuration` and `initializationOptions` in LSP). 

Also major confusion for neovim users is coming from neovim LSP directly using the `taplo-lsp` binary, where the default configuration in the binary is a different one than the one for `package.json` for the VSCode extension. 

I still didn't figure out why when using the lsp binary neither uses the `init_options` I'm passing, nor the global `~/taplo.toml`. 

Thinking in possible PRs: 
- how would a possible fix look like? same defaults for the lsp binary than in the VSCode extension? 
- which exact `initializationOptions` do need to be passed to make the schema-validation work? 
- When I figure out how it can be passed this can also be a PR to [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/taplo.lua). 


For now I'll probably use my locally hacked version until I know where to go with a fix :)

**Comment by bersbersbers** [comment]
I hope that the following error in VS Code is related to this issue, and it helps someone to find it via Google when I post this:

> failed to download schema index: error sending request: JsValue(Object({"message":"request to https://taplo.tamasfe.dev/schema_index.json failed, reason: connect ETIMEDOUT 185.199.110.153:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}))

![image](https://user-images.githubusercontent.com/12128514/151465368-251b8ab0-cb5d-480b-976a-0b8bec2bde71.png)

This leads to initial formatting being stuck for about a minute. `"evenBetterToml.schema.repositoryEnabled": false` helps.
