### ISSUE TITLE
Native LSP builds and Send bounds

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#187]
The native LSP server builds will not compile as some futures are `!Send`. The bound is required by `tokio::spawn` to support multiple threaded executions.

The simplest fix would be to use a single-threaded executor with `spawn_local` instead, multiple threads are probably unjustified anyway for any of the workloads.

**Comment by buzztaiki** [comment]
I think the implementation using `spawn_local` is sufficient.

Would you like me to implement it?

**Comment by tamasfe** [comment]
If you have the time, sure, it would be much appreciated!

Simply removing the `Send` requirements might not be enough, and additional compiler rituals might be required. As the wasm builds work, enabling the `unsend` feature on `async-lsp-stub` hopefully should be sufficient in that case.

**Comment by buzztaiki** [comment]
Yeah, OK.

I'll try to implement it in near day.
