### ISSUE TITLE
Autocomplete in `Cargo.toml` behaves weird

### ISSUE THREAD

**Issue by jplatte** [tamasfe/taplo#188]
When trying to complete `[profile.` in a `Cargo.toml`, the VSCode extension offers me a lot of suggestions of the following form:

```
profile.bench
profile.bench.build-override
profile.bench.build-override.build-override
profile.bench.build-override.build-override.build-override
profile.bench.build-override.build-override.build-override.build-override
...
```

**Comment by tamasfe** [comment]
The completions currently contain multiple levels so you don't have to type everything individually, you can simply use `foo.bar.baz` as opposed to `foo` then `bar` then `baz`.

This becomes an issue when schemas are recursive, just like the example you provided, currently there is only a hard limit for descendants, and I'm open for suggestions on how to solve this in more sophisticated ways.

**Comment by buzztaiki** [comment]
Limit to the `Cargo.toml` issue, it seems that `build-overrides` cannot have `build-overrides` attribute, so I think we should split it into two parts like `Profile` and `OverrideProfile`.

**Comment by buzztaiki** [comment]
Ah, sorry. I forgot to write the reference.

This implementation of cargo is [here](https://github.com/rust-lang/cargo/blob/ec38c84ab1d257c9d0129bd9cf7eade1d511a8d2/src/cargo/util/toml/mod.rs#L622).

**Comment by tamasfe** [comment]
The current schema was originally generated from the Cargo source, [there](https://github.com/rust-lang/cargo/blob/e1fb17631eb1b3665cdbe45b1c186111577ef512/src/cargo/util/toml/mod.rs#L411) it is the same type. I don't know if it semantically makes sense, but technically `build-override` can be nested.

**Comment by tamasfe** [comment]
Ah, just as I pressed enter, your comment appeared.

Makes sense, it would be worth it to split the types in the schema then.

**Comment by EmilySeville7cfg** [comment]
I suggest show just one nest level at once.

**Comment by tamasfe** [comment]
I personally like the current behaviour (with a correct schema of course), but it's rather easy to make it configurable so I'll do that in the next version.

**Comment by EmilySeville7cfg** [comment]
With showing one nest level _by default_. 😄

**Comment by bkchr** [comment]
@tamasfe as you closed this issue what is the name of option to change this behavior?
