### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#19]
Formatter and linter options should be configurable from an `.rc` file (`taplo.toml`?).

**Comment by sagiegurari** [comment]
in continuation of #33 I'll just ask if this could also be provided via cli args and not just rc file :)

**Comment by tamasfe** [comment]
There's now a [configuration file](https://taplo.tamasfe.dev/configuration/#configuration-file), I believe the remaining question better fits the other issue.
