### ISSUE TITLE
CLI toml-test decoder

### ISSUE THREAD

**Issue by moorereason** [tamasfe/taplo#193]
Can taplo provide a CLI [`toml-test`](https://github.com/BurntSushi/toml-test) decoder?  The decoder takes a given TOML input via STDIN and outputs annotated JSON.  Details are in the `toml-test` README.

I've been doing differential fuzzing against a few projects that implement the decoder to see where they decode things differently.

Thanks for considering.

**Comment by tamasfe** [comment]
This would be definitely welcome, TOML compliance should be pretty important for a tool that focuses on TOML.

Unfortunately I don't have time right now, if anyone wishes to implement this, I imagine the following steps would be the most straightforward:

-  implementing `serde::Serialize` for [`Value`](https://github.com/tamasfe/taplo/blob/28bdbfa134a70bf85d5c746961cfce17beef8a6e/taplo/src/value.rs#L49)
- creating a serializer that uses the format that `toml-test` expects
- finally writing a small application for it (*alternatively include it in `taplo-cli`*)

**Comment by tamasfe** [comment]
This is now implemented in `taplo-cli` on the master branch. You can install it with `cargo install --git=https://github.com/tamasfe/taplo.git --features toml-test taplo-cli`, and run it with `toml-test taplo -- toml-test`.

It has uncovered a few issues/bugs already, more in #3.
