### ISSUE TITLE
[question] New release

### ISSUE THREAD

**Issue by daxpedda** [tamasfe/taplo#195]
Since #191 was solved, I would like to use this in our CI, what are the current plans for a new release? Otherwise using the current git commit is alright too.

**Comment by tamasfe** [comment]
I've published [`tapli-cli` 0.5.0](https://github.com/tamasfe/taplo/releases/tag/release-cli-0.5.0) which includes the changes.

**Comment by daxpedda** [comment]
Amazing, thank you!
