### ISSUE TITLE
Configurable taplo.toml location

### ISSUE THREAD

**Issue by tisonkun** [tamasfe/taplo#196]
Users hosting repo on GitHub can ask for placing the effective `taplo.toml` file under `.github/` folder. Other users can also ask for avoiding placing the file under the root patch.

Besides trying to look up the config file at some pre-defined location, it's reasonable to make the location configurable.

What do you think? @tamasfe

**Comment by tamasfe** [comment]
Sorry, I missed this one. Yes, definitely would be a welcome addition in the LSP configuration!

**Comment by tisonkun** [comment]
It seems that argument isn't documented. For those who want to set a different config file, use:

```shell
taplo format -c <CONFIG>
# -c, --config <CONFIG>            Path to the Taplo configuration file
```
