### ISSUE TITLE
release-lsp-0.2.6: build problem

### ISSUE THREAD

**Issue by 0-wiz-0** [tamasfe/taplo#197]
I'm interested in the LSP server, so I downloaded release-lsp-0.2.6 and tried to build it.
First I did `cargo build` in taplo-lsp, but that didn't work, so I tried again in the top level directory.
This ended with:
```
   Compiling taplo-lsp v0.2.1 (/scratch/devel/taplo-lsp/work/taplo-release-lsp-0.2.6/taplo-lsp)
error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> taplo-lsp/bin/lsp/main.rs:50:26
   |
50 |                         .about("The address to listen on")
   |                          ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> taplo-lsp/bin/lsp/main.rs:53:39
   |
53 |                 .arg(Arg::new("port").about("Port to use").default_value("5000")),
   |                                       ^^^^^ method not found in `Arg<'_>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `taplo-lsp` due to 2 previous errors
```

1. How can I fix the build problem?
2. Why is the version number in the message v0.2.1 and not 0.2.6?
3. Can you please include Cargo.lock in the git repository? I.e. remove it from `.gitignore` and commit it (I'm not sure, but perhaps that would fix this issue)

**Comment by tamasfe** [comment]
clap seems to have new prerelease versions that broke the cli. You can force the current version with `clap = "=3.0.0-beta.2"` in the dependencies.

> Why is the version number in the message v0.2.1 and not 0.2.6?

The Cargo.toml versions can lag behind, I'm not sure how to automate updating them. The published crate versions are in the tags.

> Can you please include Cargo.lock in the git repository?

Most crates in the repo are libraries, there wouldn't be much benefit in my opinion.

**Comment by 0-wiz-0** [comment]
I tried this, adding the `=` in both the cli and lsp directories' `Cargo.toml` files, but then I got:
```
# cargo build
error: no matching package found
searched package name: `clap`
prerelease package needs to be specified explicitly
clap = { version = "3.0.0-rc.3" }
location searched: registry `crates-io`
required by package `taplo-lsp v0.2.1 (/scratch/wip/taplo-lsp/work/taplo-release-lsp-0.2.6/taplo-lsp)`
```
I read the cargo docs for a bit but couldn't find the magic string I need to use. Do you know it?

Here are the diffs I used:
```
--- taplo-cli/Cargo.toml.orig   2021-09-28 18:57:16.000000000 +0000
+++ taplo-cli/Cargo.toml
@@ -22,7 +22,7 @@ nightly = []
 
 [dependencies]
 anyhow = "1"
-clap = { package = "tamasfe-clap", version = "3.0.0-beta.2", features = ["suggestions", "std", "cargo"] }
+clap = { package = "tamasfe-clap", version = "=3.0.0-beta.2", features = ["suggestions", "std", "cargo"] }
 futures = "0.3"
 glob = "0.3"
 hex = "0.4"
--- taplo-lsp/Cargo.toml.orig   2021-09-28 18:57:16.000000000 +0000
+++ taplo-lsp/Cargo.toml
@@ -57,7 +57,7 @@ tokio = { version = "1", features = [
     "time",
     "process",
 ] }
-clap = "3.0.0-beta.2"
+clap = "=3.0.0-beta.2"
 ctrlc = "3"
 notify = "4"
 
```

**Comment by timbedard** [comment]
I will second the request for inclusion of the Cargo.lock. For the crates that libraries, I'll shrug, but anything that is meant to be built and run by itself like a CLI or LSP should definitely have a lock file for deterministic builds across systems, both developer and CI.

**Comment by tamasfe** [comment]
> I will second the request for inclusion of the Cargo.lock. For the crates that are libraries, I'll shrug, but anything that is meant to be built and run by itself like a CLI or LSP should definitely have a lock file for deterministic builds across systems, both developer and CI.
>
>It's currently not possible to cargo install taplo-lsp. You instead have to clone and build.

Cargo includes a `Cargo.lock` when an application package is published for this reason, just provide the `--locked` flag for `cargo install`.

> I will second the request for inclusion of the Cargo.lock.

Actually, thinking about it a bit, Including a `Cargo.lock` in the repository would just defer issues like this one to the point when people add any of the libraries here as a dependency, so not only it wouldn't help but it would make things a tiny bit worse.

As for this issue, I have no idea how to make progress, I would personally wait for clap3, as it seems to be just around the corner and prereleases seem to be quite volatile right now.

@0-wiz-0 do you specifically need to build `taplo-lsp` for modifications/contributions? If not, using `cargo install --locked taplo-lsp` could be sufficient.

**Comment by 0-wiz-0** [comment]
Hm, the pkgsrc infrastructure does use crates for dependencies but not for the package it builds itself - for that we currently use the github tarballs. This is the first project where I'm told that I need to use the crate to build. I'll discuss it with other rust packagers on the team.

**Comment by 0323pin** [comment]
@0-wiz-0 It builds now on 9.99.92 NetBSD 9.99.92 (GENERIC) #0: Wed Dec 15 16:27:10 UTC 2021

Built with rust-1.57.0 and forcing  clap to version 3.0.0-beta.2

**Comment by 0-wiz-0** [comment]
Thanks @0323pin . The build problem is now fixed with pinning the dependency.

**Comment by jirutka** [comment]
I will second the request for the inclusion of the Cargo.lock too. It is important for package maintainers, to ensure reproducible builds. Multiple crates in the repository is not a problem at all – cargo supports workspaces, you already use them, so just generate the parent Cargo.lock in the root of the repository. Almost all projects do it, even those using monorepo, there’s no problem.
