### ISSUE TITLE
Alter settings for a specific part of a document

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#20]
E.g. disable formatting for a few lines, or just disable sorting for a few entries, and so on.

This could be done with comments like `# taplo:ignore` but this either gets very limiting or adds too much noise in the comments.

I would much prefer a way to do this with the help of #19.

**Comment by UtkarshVerma** [comment]
Do we have any directive to disable formatting for a region or the next line?

Something like `#fmt: off` and `#fmt: on`?

**Comment by UtkarshVerma** [comment]
This is related to #724
