### ISSUE TITLE
Hang when editing Makefile.toml

### ISSUE THREAD

**Issue by hasali19** [tamasfe/taplo#219]
When editing a Makefile.toml for [cargo make](https://github.com/sagiegurari/cargo-make) the extension hangs with 100% usage of a CPU core. This doesn't seem to happen for any other toml file.

**Comment by duskmoon314** [comment]
After editing Makefile.toml, the extension seems not working on other files.

**Comment by tamasfe** [comment]
I have released a new version that is pretty much a complete rewrite, please reopen or ping me if this issue still persists.
