### ISSUE TITLE
Invalid syntax causes vscode extension to freeze entirely

### ISSUE THREAD

**Issue by LJNeon** [tamasfe/taplo#22]
I've been converting my YAML config files into TOML, so I naturally stumbled across this while renaming `.yml` files to `.toml`. Once I rename any file the VSCode extension stops working entirely. If I switch to a different TOML file it also stops for that file. Restarting VSCode appears to solve it, but this is a rather annoying bug.

**Comment by LJNeon** [comment]
Apologies for the title edits, I make a lot of typos and always correct them out of habit. I've looked into this further and it appears that the actual problem is loading a TOML file with invalid syntax. Simply opening a TOML file after inserting invalid syntax causes the same freeze. I was renaming the file extensions before I converted between formats, which triggered this.

**Comment by LJNeon** [comment]
It doesn't appear like all invalid syntax triggers this, so I'll provide a sample of syntax that does.
```toml
[group]
cooldowns = [
  {
    aggressive = true,
    duration = 20_000
  }
]
```

**Comment by tamasfe** [comment]
Thanks for the detailed issue!

It seems the parser gets into a loop if there's a new line after `{` expecting a new entry while not skipping the invalid syntax, and processing the same thing again and again.

**Comment by tamasfe** [comment]
I've pushed a fix, and a new version of the extension should be out soon. Invalid inline tables are still not handled as well as I'd like, but at least they shouldn't cause the parser to hang anymore.

**Comment by LJNeon** [comment]
Thanks for the quick fix!
