### ISSUE TITLE
Type checking fails

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tamasfe/taplo#221]
## Description

Type checking based on `type` property value fails to check whether:

- property has a correct type
- property value satisfy the provided conditions

## Steps to reproduce

1. Create `schemas/sample.toml.json`:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Sample schema",
    "description": "Validation fails property type",
    "x-taplo-info": {
        "authors": ["Emily Grace Seville (https://github.com/EmilySeville7cfg)"],
        "patterns": ["\\._config.toml$"]
    },
    "properties": {
        "sample": {
            "description": "Sample property",
            "type": "string"
        }
    }
}
```

2. Create `test/_config.toml`:

```toml
sample = 3
```

3. Create `.vscode/settings.json`:

```json
{
    "evenBetterToml.schema.associations": {
        "file:///home/emilyseville7cfg/Documents/mine/schemas/taplo/test/_config.toml": "file:///home/emilyseville7cfg/Documents/mine/schemas/taplo/schemas/sample.toml.json",
    }
}
```

4. Obtain no errors about wrong `sample` value.

**Comment by EmilySeville7cfg** [comment]
Due to this issue I can't check whether I can or not extend some schema definition like this:

```json
    "definitions": {
        "string-array-unique": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
```
and:

```json
        "exclude": {
            "description": "Exclude directories and/or files from the conversion. These exclusions are relative to the site's source directory and cannot be outside the source directory.",
            "$ref": "#/definitions/string-array-unique",
            "items": {
                "minLength": 1
            }
        },
```

**Comment by tamasfe** [comment]
The next version on the `next` branch is almost ready which is a complete rewrite that uses a proper schema validator under the hood, I think I should have it done next weekend, as most stuff left is just documentation and CI/CD changes.

> Due to this issue I can't check whether I can or not extend some schema definition like this:

Don't, the new [validator](https://github.com/Stranger6667/jsonschema-rs) only supports draft 7, which should ignore anything beside a `$ref`according to the spec. You should be able to use `"allOf": [ { "$ref": "..." } ]` for similar effects however.

**Comment by tamasfe** [comment]
> I think I should have it done next weekend, as most stuff left is just documentation and CI/CD changes.

Yeah this part did not quite work out.

I have just released new versions eveywhere, please reopen this if the problem still persists.
