### ISSUE TITLE
Add a schema for `.cargo/config.toml` and `rust-toolchain.toml`

### ISSUE THREAD

**Issue by ian-h-chamberlain** [tamasfe/taplo#228]
Hi, the VSCode extension is super useful for discoverability in things like Cargo.toml and Makefile.toml. I would like to add a schema for `.cargo/config.toml` as well.

If someone is not already working on this, I can try to take a stab at writing the schema, but wanted to make sure I'm not repeating someone else's work by opening this issue.

There are quite a few fields allowed in `config.toml`: https://doc.rust-lang.org/cargo/reference/config.html#configuration-format
So most likely, the schema would be somewhat incomplete to start out, but I think it could still be useful. Let me know what you think!

**Comment by ian-h-chamberlain** [comment]
Additionally, I would like to add one for `rust-toolchain.toml`. This is a much smaller schema and I could probably contribute this first as a way to get my feet wet writing TOML schemas (I have a local one that mostly works so far).

**Comment by tamasfe** [comment]
Hi, I'm not aware of anyone working on this, and would be very much welcome!

**Comment by tamasfe** [comment]
Thank you for these so far!

The tools now support the schema store and new schemas should be submitted there instead. ([docs](https://taplo.tamasfe.dev/configuration/developing-schemas.html#publishing))

**Comment by ian-h-chamberlain** [comment]
@tamasfe Thanks for the update! In case there are any bugfixes / updates needed to the existing schema, should I still submit them to this repo? Or do you plan to avoid maintaining them at all in favor of the schema store?

**Comment by tamasfe** [comment]
The schemas should be submitted to the schema store in all cases. I'm planning to submit the schemas I authored to the store as well (`Cargo.toml` and `pyproject.toml`), I don't think there's any benefit in storing them in this repo since I consider them public domain.

The catalog available via the website is there so that the existing schemas continue to work, but I don't plan to update it in any way.
