### ISSUE TITLE
Reported errors in VSCode aren't removed when files are deleted.

### ISSUE THREAD

**Issue by LJNeon** [tamasfe/taplo#23]
When a TOML file with syntax errors is deleted, the errors aren't removed and persist in the folder icon and problems tab. I'll attach screenshots below.
![image](https://user-images.githubusercontent.com/23249107/86145868-561b6a80-baac-11ea-91d0-a0c0b15d82f7.png)
![image](https://user-images.githubusercontent.com/23249107/86146838-8d3e4b80-baad-11ea-993e-b1aef36e4ab6.png)

**Comment by tamasfe** [comment]
Document close events are ignored in the server, in fact this could lead to memory leaks as well, but it should be rather trivial to fix. I'll get to it soon.
