### ISSUE TITLE
Support inline `$schema` definitions

### ISSUE THREAD

**Issue by davidkna** [tamasfe/taplo#230]
JSON-files that follow a JSON-schema often include a reference to the schema.
```json
{
  "$schema": "https://starship.rs/config-schema.json"
}
```

Please also support this for TOML files:
```toml
"$schema" = 'https://starship.rs/config-schema.json'

```

[jsonschema](https://github.com/Stranger6667/jsonschema-rs) seems to support doing this (#211).

**Comment by tamasfe** [comment]
This is implemented in the next version (read more in #231).
