### ISSUE TITLE
Bug: new version clears Cargo.toml

### ISSUE THREAD

**Issue by rgnkn** [tamasfe/taplo#236]
I'm not sure if this is the right repo to report this though I guess it is.

I'm using `neovim` with `neoformat` for  autoformatting. Everything worked fine so far, but with the new version v0.6 my Cargo.toml (I guess all toml files) basically gets whiped out / cleared on save.

Therefore I needed to switch back to v0.5 where everything works fine.

Is this a known bug or do I need to set something new which I have missed?

[EDIT] I build with cargo 1.61.0-nightly (109bfbd 2022-03-17).

**Comment by tamasfe** [comment]
Can you reproduce it via the CLI or is this a regression in the lsp?

**Comment by rgnkn** [comment]
I just checked:

If I run the formatting via the terminal (`taplo format Cargo.toml`) it seems to work as expected.

Do you have any idea what could trigger the "deletion" when using it via `neovim`? I ask this as you mentioned lsp.

If you might give me a hint, I may be able to search for a solution.

**Comment by rgnkn** [comment]
I just checked:

[lsp_installer](https://github.com/williamboman/nvim-lsp-installer) seems to use https://github.com/kkiyama117/taplo which is "a bit" outdated.

Do you know of any alternative or is there any plan to find a new maintainer for this?

**Comment by rgnkn** [comment]
[UPDATE]:

I just tried to format in neovim after `:LspStop`. The problem remains with v0.6.

**Comment by rgnkn** [comment]
Okay, I tracked it down and this really seems to be a bug in taplo v0.6:

This is what it looks like if format via `stdin` in v0.5:

![Screenshot from 2022-03-30 12-04-29](https://user-images.githubusercontent.com/17874137/160806882-aa176544-fab2-419c-8536-47ea30c19add.png)

And this is how it looks in v0.6:

![Screenshot from 2022-03-30 12-02-38](https://user-images.githubusercontent.com/17874137/160806984-61ea036a-2248-4f98-ac45-7cbe5afd18a1.png)

It basically doesn't seem to format via `stdin`.

Please, confirm.

**Comment by koalp** [comment]
I have the same issue.

For me it formats using stdin but outputs to stderr instead of stdtout in 0.6 : 

Running this command 
```
cat Cargo.toml | cargo run --bin taplo fmt - 2>/dev/null
```
shows the formated output in 0.5 but not in 0.6

**Comment by rgnkn** [comment]
@koalp 

I didn't check that, but you're right!

**Comment by koalp** [comment]
If I change this line from `stderr` to `stdout` it works again : https://github.com/tamasfe/taplo/blob/master/crates/taplo-cli/src/commands/format.rs#L54

**Comment by rgnkn** [comment]
> If I change this line from `stderr` to `stdout` it works again : https://github.com/tamasfe/taplo/blob/master/crates/taplo-cli/src/commands/format.rs#L54

You were a minute quicker.

Confirmed!

@tamasfe Can you amend this as I guess that this might effect many users? The neovim user base isn't that small.

**Comment by tamasfe** [comment]
Yes, it's a typo in the code, the output is supposed to go to stdout.

I won't be near a PC till the weekend, PRs are welcome, and if I can I'll merge+do a release from phone.

**Comment by koalp** [comment]
I’ve created a pull request fixing this issue and another minor issue.

I also bumped the issue in a commit. Not sure if you wanted to do it yourself or not. I can remove the commit.
