### ISSUE TITLE
Section names "inherit" links of their children

### ISSUE THREAD

**Issue by Aloso** [tamasfe/taplo#24]
When hovering over a section name, it displays the links of its children:

![too many links](https://user-images.githubusercontent.com/15658558/86181155-cd451300-bb2d-11ea-9bb6-67f29535b85c.png)

**Comment by tamasfe** [comment]
Ugh, there are so many things wrong with this. The keys of the features aren't even supposed to have links.

**Comment by Aloso** [comment]
Is this supposed to be fixed in 0.7.2? Because I the bug is still present for me (at least in VS Code).

Maybe it would be better to remove the links and add them only to the hover menu? This would also remove the underlines.
