### ISSUE TITLE
Distributing static binaries

### ISSUE THREAD

**Issue by jsierles** [tamasfe/taplo#248]
We're now using Taplo for `fly.toml` validation at Fly.io. It's great to have support in VSCode. Thanks for this project!

We're also looking into validation in our CLI which is a Golang project. Go doesn't appear to have a project as well-developed as this one, so I thought we could look into using taplo as a 'plugin'. Does it make sense to try setting up static binaries for this purpose?

**Comment by tamasfe** [comment]
Hi, in theory you could use cgo to interface with taplo, however the library was not made with this in mind and you would have to write Rust side of the FFI as well.

If your CLI is purely a Go application, I would not recommend doing this at all, and even if you already use cgo, it'd be still cumbersome and you'd need to introduce the Rust toolchain in your deployments.

You'd probably better off with converting the TOML files to JSON and validating that while staying within the Go ecosystem. (This is essentially what taplo does for validaiton in the newest CLI but utilizing libraries written in Rust.)

**Comment by tamasfe** [comment]
I'll close this as I'm cleaning up issues, and this is unactionable on my part, feel free to ask further questions if you have any.
