### ISSUE TITLE
support install taplo-cli with homebrew

### ISSUE THREAD

**Issue by zanglg** [tamasfe/taplo#251]
That would be nice if ``taplo-cli`` can be installed with ``home-brew``, that I can easily update all my binary tools with ``brew upgrade``. Cargo also can install and update, but I have some issue to compile openssl. Considering that brew was the most common used package tool, it's worth to do.

**Comment by tamasfe** [comment]
I've never used homebrew and distribution via various package managers would involve way too much maintenance burden for me anyway. It's not something I would like to do right now. 

Feel free to ping me if you have taplo packaged in some shape of form and want me to list it in the readme or website.

**Comment by jasikpark** [comment]
For context: as of Aug 16, there has been no homebrew bottle published for `taplo-cli`

I would make one, if I used the cli instead of using the VSCode extension + wishing there was a prettier plugin I could install as a dep of my projects

**Comment by messense** [comment]
Done in https://github.com/Homebrew/homebrew-core/pull/109558#event-7317112010

**Comment by tamasfe** [comment]
Thanks!

**Comment by jasikpark** [comment]
maybe it can be linked in the docs now :p

**Comment by zanglg** [comment]
Thanks, closed.
