### ISSUE TITLE
committing the lockfile?

### ISSUE THREAD

**Issue by happysalada** [tamasfe/taplo#254]
would you consider commiting the lockfile ?
this helps to package this tool for other distributions

**Comment by tamasfe** [comment]
I've rejected this once because taplo can be used as a library it's harder to catch possible dependency breakages in CI.

I'm curious in what situations would a lockfile outside `crates.io` help?

**Comment by happysalada** [comment]
With a compilation from source, if something fails it's usually easier to manipulate the github source (you can fork and test different things. It's also possible to just manipulate the source after a download from crates.io, just harder).
For now nixos is using the crates.io source so not a problem. Hopefully there never is a need to fix a compilation problem (to be clear sometimes there are problems just because nix tries to do things in a reproducable way. For example, it tries to build a vendor directory for dependencies. Sometimes it doesn't work well with some projects even though the normal cargo build works perfectly fine).
Thank you for the context!
I'll re-open the issue if there is a real need for it.
Thank you for the software also :-)
