### ISSUE TITLE
Rewrite Feature request: #:schema header

### ISSUE THREAD

**Issue by Profpatsch** [tamasfe/taplo#255]
We are using the `#:schema ./path/to/file` header quite heavily (for referencing schemas relative to the file, the schemas are in the same repository).

I noticed that there was an essentially total rewrite, but support for `#:schema` hasn’t been added back yet. This is just a feature request for it (or a similar feature, we can adapt it) before the vscode extension gets updated.

**Comment by Profpatsch** [comment]
Also the CLI version never understood `#:schema` I’m finding out, which I’m currently patching into the older cli version for running it as a lint on CI.

**Comment by tamasfe** [comment]
The currently published vscode extension is before the rewrite, the rewritten one has some regressions regarding completions and I don't want to throw off users who are happy with the old extension. However it will have the feature you need.

On the other hand, adding the feature to the new CLI should be rather easy and omitting it was probably an oversight on my part.

**Comment by Profpatsch** [comment]
No worries, we’ll stay on the old version until the new vscode extension is released anyway. According to microsoft it has >150k downloads, that’s quite a heavy usership!

**Comment by tamasfe** [comment]
With the new release this should be working everywhere ([docs](https://taplo.tamasfe.dev/configuration/using-schemas.html)).

**Comment by Profpatsch** [comment]
Ah great!

What is the difference between using a schema directive in a comment and the `$schema` key?

**Comment by tamasfe** [comment]
Both behave the same, `$schema` is actually part of the data though so it will be visible to most TOML libraries and tools and will be preserved by tools that strip comments.
