### ISSUE TITLE
Request: Opt-out of collapsing multiple lines of whitespace between sections

### ISSUE THREAD

**Issue by atc0005** [tamasfe/taplo#26]
I'm really enjoying working with this extension, but when I save a modified TOML file I find that multiple lines (two in my case) of whitespace between sections are collapsed into one.

I looked, but didn't find an existing setting to opt out of this behavior. Is there an option for this that I've overlooked?

Thanks in advance and also for creating the `Even Better TOML` VSCode extension!

**Comment by tamasfe** [comment]
Thank you, I'm glad you like it!

I will add a setting for max allowed empty lines, it should be trivial to implement.

I don't know when as I'm a bit overwhelmed with other projects right now, but I'll make some time for this eventually.

**Comment by tamasfe** [comment]
I've added the `evenBetterToml.formatter.allowedBlankLines` option, and bumped the default to `2`. 

The new version is not yet released, as I'm still working on it, but I'll release it today.

**Comment by atc0005** [comment]
@tamasfe That's awesome, thanks!
