### ISSUE TITLE
avoid using a schema

### ISSUE THREAD

**Issue by axdank** [tamasfe/taplo#261]
How can I disable the use of a schema in `.taplo.toml`, I have a file called `theme.toml`, but I get errors because it automatically uses the schema of `https://schemas.wp.org/trunk/theme.json`, which is not required and does not correspond to my file, I have tried several ways and I can not exclude.

```log
{"jsonrpc":"2.0","method":"taplo/didChangeSchemaAssociation","params":{"documentUri":"file:///D:/**/**/theme.toml","schemaUri":"https://schemas.wp.org/trunk/theme.json","meta":{"name":"theme.json","description":"WordPress block theme global settings and styles configuration file","source":"catalog","catalog_url":"https://www.schemastore.org/api/json/catalog.json"}}}
```

![image](https://user-images.githubusercontent.com/55039048/172233111-763b8e0c-4e07-4bd1-96fa-19bc2982ca49.png)

**Comment by tamasfe** [comment]
This should be fixed in the latest releases.
