### ISSUE TITLE
syntax highlighting inconsistent for single-quoted string keys

### ISSUE THREAD

**Issue by tedbyron** [tamasfe/taplo#263]
two examples from the same file:

![image](https://user-images.githubusercontent.com/39110425/173117231-e7517640-9856-46f8-8db0-072bbf104f92.png)

![image](https://user-images.githubusercontent.com/39110425/173116934-dc64f66c-9b1f-4e4b-8ad3-12622d665a0c.png)

**Comment by tamasfe** [comment]
It's not inconsistent in a sense that a string literal is in fact a key and should be coloured like the other keys. It's more apparent when the keys are not white:
![image](https://user-images.githubusercontent.com/25967296/174169615-7d3d5d36-cca5-46e0-858f-38c19ca178f1.png)

Whether string literals in key positions should be keys or string literaly primarily is debatable. I cannot make it easily configurable, so I'd wait for input from others as well.

**Comment by tamasfe** [comment]
Actually, nevermind. I misunderstood the issue.

**Comment by tamasfe** [comment]
This should be fixed in the newest version.
