### ISSUE TITLE
Taplo CLI: --quiet flag removed?

### ISSUE THREAD

**Issue by jason5122** [tamasfe/taplo#264]
Hi, for the latest version of `taplo` (0.6.6), has the `--quiet` flag been removed? I remember using it in 0.3.2.

Currently, it seems like there is no way to suppress debug output for `taplo format` — it will print to stderr:
```
INFO taplo:format_stdin:load_config: found configuration file path="/path/to/config"
```

**Comment by jasonhan-vassar** [comment]
Makes sense. Thanks for the help!
