### ISSUE TITLE
Color render bug of ">="

### ISSUE THREAD

**Issue by hktkzyx** [tamasfe/taplo#267]
Even Better Toml: 0.15.2
VSCode
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

I find a bug when toml file contains ">=", like
![image](https://user-images.githubusercontent.com/29121836/174219708-0d64e297-b3ec-4535-802e-e65c40014b23.png)

**Comment by tamasfe** [comment]
Thanks, this should be fixed in the newest version.
