### ISSUE TITLE
Something broke in v0.16.1

### ISSUE THREAD

**Issue by AaronKutch** [tamasfe/taplo#269]
The most recent update changed whatever the keys (whatever the term is in toml) are classified as which messes up color theming. I don't know what it is, but in most themes the keys and value colors are much closer than before. Also, whenever I have a lot of Cargo.toml files open, sometimes the keys are all underlined in some files
![image](https://user-images.githubusercontent.com/32419308/174356772-f821a40d-8d2d-4ed6-8bed-fa9cb44c8af4.png)
I can't get a reproducible setup for the underlining issue, it is very inconsistent and seems to happen upon adding a folder to a large workspace.

**Comment by AaronKutch** [comment]
It seems just adding at least two large Rust repos to a workspace does the trick somewhat consistently. Try [awint](https://github.com/AaronKutch/awint) followed by [rust](https://github.com/rust-lang/rust) followed by any other Rust repo, and on the third one some of the toml files will underline

**Comment by tamasfe** [comment]
> I don't know what it is, but in most themes the keys and value colors are much closer than before.

It's the change in https://github.com/tamasfe/taplo/pull/210, there just wasn't a release since.

The link issue is quite weird, I haven't been able to reproduce it yet. Can you see whether explicitly disabling them affects anything? (`"evenBetterToml.schema.links": false`)

**Comment by AaronKutch** [comment]
Disabling them still results in the underlining. I figured out a more reproducible way, and it only happens with the extension activated. Start with no workspace open, open a folder, click on a `.toml` file in that folder to have it viewed in a window, add another folder to the workspace, click on the second `.toml` file, and then it has the weird underlining thing

**Comment by tamasfe** [comment]
Thank you, managed to reproduce it.
