### ISSUE TITLE
How to start taplo lsp now

### ISSUE THREAD

**Issue by Decodetalkers** [tamasfe/taplo#271]
I font that taplo lsp stdio does not work anymore

**Comment by tamasfe** [comment]
It works the same way, it's not a default feature anymore though. If you're installing it via cargo you'll have to pass the `--feature lsp` flag.

**Comment by Decodetalkers** [comment]
> It works the same way, it's not a default feature anymore though. If you're installing it via cargo you'll have to pass the `--feature lsp` flag.

Thanks

**Comment by tamasfe** [comment]
I added a section about this on the website, the cli will also throw an appropriate error about it.

**Comment by ccqpein** [comment]
@tamasfe Thanks! I cannot start lsp then find this issue.
