### ISSUE TITLE
No syntax highlighting on One Dark Pro

### ISSUE THREAD

**Issue by stingalleman** [tamasfe/taplo#276]
Hi, thank you for the extension. It works great - except that I don't have any syntax highlighting on the One Dark Pro theme. It seems to work on other themes though.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/13184132/174921982-0127741d-e8dc-4ff6-8e9e-f96fb909c0e2.png">

**Comment by tamasfe** [comment]
Hi, it's a theme issue, I can't do much about it. We use the same scope as JSON keys, but the theme seems to have a color override explicitly for JSON only.

You can either fix the theme or set a color for `support.type.property-name.toml` manually.
