### ISSUE TITLE
Feature request: add Rules in settings.json for vscode

### ISSUE THREAD

**Issue by GilShoshan94** [tamasfe/taplo#281]
Hi,

While it is nice to have option and to have a config file for `taplo`, I like having all my ide settings inside the `settings.json` of vscode. And so far they are all here beside the ["Rules"](https://taplo.tamasfe.dev/configuration/file.html#rules).
Would it be possible to add the rules into a new setting please?

I was thinking something like this:
```jsonc
// ## Even Better Toml, general config
"evenBetterToml.formatter.alignComments": true,
"evenBetterToml.formatter.alignEntries": false,
"evenBetterToml.formatter.reorderKeys": false,
...
// ## Rules that overwrite the above configuration based on some conditions
"evenBetterToml.rules": [
    { // First rule, full example
        "include": [
            "Cargo.toml",
            "**/Cargo.toml"
        ],
        "exclude": [],
        "schema": {
            "path": "https://example.com/my_schema.json",
            "enable": true
        },
        "keys": [
            "dependencies",
            "dependencies.*",
            "*.dependencies"
        ],
        "formatting": {
            "reorderKeys": true
        }
    },
    { // Second rule, reorder all keys for `another_config.toml`
        "include": [
            "another_config.toml"
        ],
        "formatting": {
            "reorderKeys": true
        }
    }
],
...
```

(This is basically a translation from the TOML config to the JSON format).

**Comment by tamasfe** [comment]
I implemented this in db14861f33204f3671943e2d8bc83c9947ee5daa, should be available in the next version.

**Comment by GilShoshan94** [comment]
Thank you so much !

**Comment by pe224** [comment]
Is it working on Windows now? What is the exact config you used in the end? It's not working for me and it seems the `rules` part specifically for VSCode settings is still largely undocumented
