### ISSUE TITLE
Migrate schemas to schemastore.org

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#288]
I have deprecated Taplo's own schema catalog since a [jsonschema](https://github.com/Stranger6667/jsonschema-rs) implementation has been merged opening up much wider support for official schema drafts and schemas don't have to be crafted for Taplo specifically.

I don't intend to accept new schemas or improvements in this repository, if you wish to submit changes, please join the ongoing effort of merging schemas into the schema store, or if you have an idea for a new schema, submit there directly instead.

The most recent migration effort I know about is [here](https://github.com/hyperupcall/schemastore/tree/add-schemas-taplo).

**Comment by hyperupcall** [comment]
The schemas have successfully Merged into SchemaStore 🥳

**Comment by tamasfe** [comment]
Thank you!
