### ISSUE TITLE
[Feature Request] Pre-built binary for aarch64

### ISSUE THREAD

**Issue by 4513ECHO** [tamasfe/taplo#289]
Thanks a lot for great language-server!
I currently use computer which is `linux` and `aarch64` ( `arm64` ), and install taplo from cargo.
I want to download pre-built binary from GitHub Release.

**Comment by 4513ECHO** [comment]
I think [`cargo-zigbuild`](https://github.com/messense/cargo-zigbuild) is useful for cross-compiling.

**Comment by tamasfe** [comment]
If it's possible, we could also use arm on github actions instead. I'm not sure whether to bother with cross compiling is worth it in that case.

Anyway I'm fine with cross-compiling as well, but unfortunately the only arm machine I have is my phone, which is not ideal for testing. So yeah, PRs are appreciated!
