### ISSUE TITLE
Add support for workspace inheritance

### ISSUE THREAD

**Issue by campbellcole** [tamasfe/taplo#292]
As per the newly merged https://github.com/rust-lang/cargo/issues/8415

Keys in `[package]` and `[dependencies]` need to support `{key}.workspace = true`

**Comment by tamasfe** [comment]
For anyone who wants to tackle this, the schema is hosted at schemastore: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/cargo.json

**Comment by TennyZhuang** [comment]
What's the status of the issue? I'd like to take a try.

**Comment by tamasfe** [comment]
I'd assume no one is working on it right now.

**Comment by TennyZhuang** [comment]
I've submitted a draft PR https://github.com/SchemaStore/schemastore/pull/2442 for partial support the feature. How can I test with taplo? I will finish the PR if I'm sure it can work well.

**Comment by tamasfe** [comment]
> How can I test with taplo?

The I way I usually do it:

In a directory:
```
schema.json
test.toml
```

Then in `test.toml`:

```toml
#:schema ./schema.json

```

Make sure to set `evenBetterToml.schema.cache.diskExpiration` and `evenBetterToml.schema.cache.memoryExpiration` to some low value so that the schema is always reloaded as you edit it.

**Comment by TennyZhuang** [comment]
The PR is merged, so most fields are supported with the plugin except `workspace.dependencies`. It's a bit more complex and I may investigate for that later.

**Comment by TennyZhuang** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/9161438/187487448-27cf5bf3-f016-498a-8c38-31443b358e2e.png">

I guess we can close the issue as completed!

**Comment by tamasfe** [comment]
Thank you!
