### ISSUE TITLE
taplo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by David-Else** [tamasfe/taplo#306]
I would like to use the language server, I install the latest binary `taplo-full-x86_64-unknown-linux-gnu.tar.gz`  but get:

```
taplo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file
```
I am using AlmaLinux 9. I tried installing `openssl-devel` but it made no difference.

Also, is the full version available on NPM? I can't find any mention of it. Thanks.

**Comment by tamasfe** [comment]
The next version (hopefully tomorrow) will not depend on openssl, meanwhile installing just the `openssl` package should probably be sufficient.

> Also, is the full version available on NPM? I can't find any mention of it. Thanks.

It's not currently, it would take more effort to expose the language server via a javascript CLI and providing both a "minimal" and full version via NPM as well would further complicate the release process so I decided not to do it.

**Comment by David-Else** [comment]
I have `openssl` installed, so that was not the problem:
```
Name         : openssl
Epoch        : 1
Version      : 3.0.1
Release      : 23.el9_0
Architecture : x86_64
Size         : 1.8 M
Source       : openssl-3.0.1-23.el9_0.src.rpm
Repository   : @System
From repo    : baseos
Summary      : Utilities from the general purpose cryptography library with TLS implementation
URL          : http://www.openssl.org/
License      : ASL 2.0
Description  : The OpenSSL toolkit provides support for secure communications between
             : machines. OpenSSL includes a certificate management tool and shared
             : libraries which provide various cryptographic algorithms and
             : protocols.
```
I will check back tomorrow for the new version, cheers.

**Comment by tamasfe** [comment]
Sorry for taking this long, a new release (`0.7.0`) is out now, reopen this if the issue persists for some reason.

**Comment by David-Else** [comment]
New version `0.7.0` works, thanks!
