### ISSUE TITLE
Compile CLI on WASM

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#307]
#301 introduced the `prettydiff` dependency which depends on `ansi_term` that won't compile on WASM nor seems to be maintained.

This currently blocks all javascript releases (cli/lib/lsp/vscode).

Currently we can do any of the following to resolve this:
1. Remove the `--diff` feature from the javascript CLI wrapper, it's hacky and might come as a surprise to users, but probably the fastest.
1. Remove the `--diff` feature altogether for now, I definitely do not want this.
1. Look into an alternate `--diff` implementation that does not depend on `ansi_term`.
1. Fork `ansi_term` and patch it for wasm builds, even more hacks but still viable.

@drahnr can you perhaps help me out with this one?

**Comment by drahnr** [comment]
`ansi_term` is a dep of `pretty-diff`. We could replace it by `diff-rs` . So I'd opt for 1. to unblock, and then replace the offending does with smith else.
