### ISSUE TITLE
`Even Better TOML` considers `version = {workspace=true}` in `Cargo.toml` as an error

### ISSUE THREAD

**Issue by BLucky-gh** [tamasfe/taplo#309]
Rust has already stabilized the `workspace-inheritance` feature in the beta branch that's set to be released on stable in september, but the extension (the repo of which points to here) shows an error when I actually use that feature:
``{"workspace":true} is not of type "string"``

Slightly related issue:
`{"channel":"beta","components":["rustfmt","clippy"],"targets":["wasm32-unknown-unknown","x86_64-apple-darwin"]} is not valid under any of the given schemas` when using a `rust-toolchain.toml` with the newer toml syntax instead of the older "just put the toolchain name in there" syntax

**Comment by TennyZhuang** [comment]
Duplicated #292
