### ISSUE TITLE
Rules are not working

### ISSUE THREAD

**Issue by Bludator** [tamasfe/taplo#321]
The [rules](https://taplo.tamasfe.dev/configuration/file.html#rules) are not working, (at least) in the current version of the VSCode extension on both windows and linux. Formatting or schemas are not applied.

By changing versions of the extension I have found it stopped working with version `v0.17.0`.

**Comment by mdeville** [comment]
I also confirm that the bug exists

**Comment by Bludator** [comment]
I don't think it is fixed. Could you check it works for you? If so, I will provide example repo.

**Comment by Bludator** [comment]
Thank you

**Comment by tamasfe** [comment]
Sorry about the delay and the silence, I am a bit all over the place.

**Comment by jacek-jablonski** [comment]
Still not working in `v0.19.0`
