### ISSUE TITLE
No support for inline comments on table arrays?

### ISSUE THREAD

**Issue by alxpettit** [tamasfe/taplo#325]
When I tried running tapio against [this](https://raw.githubusercontent.com/Lothrazar/AbsentByDesign/trunk/1.18/src/main/resources/META-INF/mods.toml) file, it gave me the following error message:

```
 INFO taplo:format_files:collect_files: found files total=1 excluded=0 cwd="[REDACTED]"
error: invalid TOML
   ┌─ /tmp/META-INF/mods.toml:14:9
   │
14 │ [[mods]] #mandatory
   │         ^ expected new line

error: invalid TOML
   ┌─ /tmp/META-INF/mods.toml:36:32
   │
36 │ [[dependencies.absentbydesign]] #optional
```
It's taplo 0.7.0, installed via Arch repos.

**Comment by tamasfe** [comment]
It's a bug, same as #315.
