### ISSUE TITLE
standalone formatter

### ISSUE THREAD

**Issue by sagiegurari** [tamasfe/taplo#33]
can this be packaged as a binary crate and be used as a toml formatter?
getting a glob path and than formatting all toml files based on that path?

**Comment by tamasfe** [comment]
Yes, I've started working on a cli tool. A lot of it is already written, but #19 needs to be done simultaneously, and it will involve some changes in the extension as well, and I'd like to refactor the repo as a whole a bit while I'm at it.

I think I'll have a _usable version_ of it by this weekend.

**Comment by sagiegurari** [comment]
thanks a lot. can't wait

**Comment by tamasfe** [comment]
@sagiegurari I ended up not having a lot of time, and I will need a few more hours probably. I've pushed the progress so far to a [`cli` branch](https://github.com/tamasfe/taplo/tree/cli) in case you really need this feature asap and would like to help with it.

**Comment by sagiegurari** [comment]
Thanks for the update. I'll wait for the official release so i'll be able to test with standard installation flow.

my main goals are
1. format my toml files naturally. got lots of those as apart of the Cargo.toml, i also have all the Makefile.toml files (especially [inside cargo-make](https://github.com/sagiegurari/cargo-make/tree/master/src/lib/descriptor/makefiles)).
2. write a format toml task inside cargo-make so all projects using cargo-make will automatically have access to this capability. (much like [rustfmt format task](https://github.com/sagiegurari/cargo-make/blob/2f1666bae923ba9bda984077e2532f1dad621671/src/lib/descriptor/makefiles/rust.toml#L212)

however to get there i'll need
1. a very consistent toml formatter. meaning spacing, end of lines and all that would not break if i just write things too messy.
2. ability to pass config via command line. if the task is defined inside cargo-make Makefile.toml than people can just configure it there via the formatter cli instead of having multiple config files.
I see many people do the same thing for clippy for example.
3. nice to have - later on, we can expand that on having a --check flag to make sure toml is formatted (good for CI)

there was another rust based toml formatter i tried long ago, but it wasn't active and the formatting didn't always work.
happy I have another shot at it :)

**Comment by tamasfe** [comment]
@sagiegurari Sorry, it took way longer than I expected, there is now a [CLI tool](https://taplo.tamasfe.dev/cli/#installation), however I haven't implemented passing formatter options because it needs additional arg parsing work.

I'm thinking along the lines of a`--format-options option1=true,option2=20 ...` flag, would that work for you?

**Comment by sagiegurari** [comment]
thanks a lot. i'm checking it out :)

**Comment by sagiegurari** [comment]
works amazing, really fast and great defaults. love it.
i'm going to put some default tasks inside cargo-make for it, i'll update this issue when done if you will be interested.

**Comment by sagiegurari** [comment]
Just updated [cargo-make 0.32.9 branch](https://github.com/sagiegurari/cargo-make/tree/0.32.9) with few tasks to do toml formatting.
Basically you can now run:

```sh
cargo make format-toml
```

But more I updated the default task to always format toml files as well.
I'll probably officially release it once you resolve those 2 small issues I opened.
thanks a lot for the great tool. I was looking for such a thing for a long time.

**Comment by tamasfe** [comment]
@sagiegurari they should be fixed in `0.1.1`, I think this issue has served its purpose. Feel free to created an issue if you need anything, I also created #55 to discuss formatting option arguments.
