### ISSUE TITLE
vscode Even Better TOML: Authors regex pattern for validation of pyproject.toml doesn't match email addresses surrounded by <>

### ISSUE THREAD

**Issue by tbradshaw** [tamasfe/taplo#34]
When using Even Better TOML with vscode, I noticed that my author byline wasn't matching.

I had written: `authors = ["Travis Bradshaw <travis@tbradshaw.net>"]`, which created an error that reads "the value doesn't match the given pattern".

I found the regex in the source to perform a cursory check, but after pasting the regex into a couple online validators it didn't seem to parse for them.  (I think maybe this is a flavor of regex that the online validators didn't support?  The discrepancies appeared to be very minor, but the regex for matching this field is a bit of a whopper and so I didn't investigate further.)

Through just trial and error, I found that "Travis Bradshaw travis@tbradshaw.net" does work, but "Travis Bradshaw <travis@tbradshaw.net>" does not.

Checking the spec for pyproject.toml, I think that this is in error: https://www.python.org/dev/peps/pep-0621/#authors-maintainers

Thank you for your time,

-- Travis

**Comment by tamasfe** [comment]
Thanks, it is just an email regex with mandatory whitespace before it, and I apparently forgot to add the `<>`.
Also currently `" some@email.com"` will be valid, but it shouldn't be.

These should be small fixes but I don't have any time for this project right now.

A PR would be very welcome if you have some time.

The regex that is releated is [here](https://github.com/tamasfe/taplo/blob/master/taplo-ide/schemas/pyproject.yaml#L77), same one is used for `maintainers`, thus it is also incorrect.

**Comment by tbradshaw** [comment]
Thank you!
