### ISSUE TITLE
failed to set environment variable `"LANGUAGE"` to `"zh_CN:en"`: cannot set env vars on this platform

### ISSUE THREAD

**Issue by MaxKingPor** [tamasfe/taplo#341]
VSCode SSH Connects to Ubuntu remotely
* Even Better TOML Version v0.18.2

![image](https://user-images.githubusercontent.com/43533178/197730992-15f38d0f-8683-428b-82aa-9ecf4b45cdce.png)

**Comment by mdeville** [comment]
Seems like the LSP crashes when setting any env var. I'm on VSCode SSH also

**Comment by tamasfe** [comment]
As the error suggests, this was caused by trying to set env vars inside WASM, I've just published a fix.
