### ISSUE TITLE
Question: Is it possible to configure `[features]` lists?

### ISSUE THREAD

**Issue by NunoAlexandre** [tamasfe/taplo#342]
Hey!

Thanks for developing `taplo`. I am working on introducing it to our repo at https://github.com/centrifuge/centrifuge-chain/pull/1055 and one feature that seems missing is the capability to also sort lists under `[features]`. For example, the `std` feature list [here](https://github.com/centrifuge/centrifuge-chain/blob/main/runtime/centrifuge/Cargo.toml#L131-L219).

Am I missing how to achieve that or is it really not supported at them moment? Thank you!

**Comment by tamasfe** [comment]
Hi, if you are looking to sort values in an array, it's indeed not a feature yet. However it might become one in the near future, it's tracked in #158.

**Comment by NunoAlexandre** [comment]
sweet, thank you 🚀
