### ISSUE TITLE
Error when using Inline Table with Multiple Keys

### ISSUE THREAD

**Issue by mattaltberg** [tamasfe/taplo#345]
I'm currently getting the following error:

```
{"test":"data", "test2":"data2"} is not of type "array"
```

when using the following in my TOML file:
```
table = {test = "data", test2 = "data2"}
```

Note that the following works:
```
test = {a = "b"}
```

**Comment by tamasfe** [comment]
It looks like a schema validation error. What schema are you using?

**Comment by mattaltberg** [comment]
pyproject.toml

I think I've misunderstood what the `authors` field is asking for 😆
