### ISSUE TITLE
gzipped full Windows x86_64 0.8.0 release file seems corrupted

### ISSUE THREAD

**Issue by dotdash** [tamasfe/taplo#351]
```
$ sha256sum taplo-full-windows-x86_64.gz
0593d3694340965b00171f1456d28f53b4a731ed42f7861cb936f2d9c0e308f4  taplo-full-windows-x86_64.gz

$ gunzip taplo-full-windows-x86_64.gz

gzip: taplo-full-windows-x86_64.gz: not in gzip format

$ file taplo-full-windows-x86_64.gz
taplo-full-windows-x86_64.gz: data
```

Others are seeing the same problem, e.g. https://github.com/mattn/vim-lsp-settings/issues/642#issuecomment-1307439850

**Comment by williamboman** [comment]
I'm experiencing the same (see for example [this failed workflow](https://github.com/mason-org/mason-registry/actions/runs/3689822189/jobs/6246197250)).
