### ISSUE TITLE
Extension complains about upper-case email addresses

### ISSUE THREAD

**Issue by Vuizur** [tamasfe/taplo#360]
For example, the extension complains about the line in my pyproject.toml
authors = ["Vuizur <Vuizur@users.noreply.github.com>"]

But if I change it to:
authors = ["Vuizur <vuizur@users.noreply.github.com>"]
everything works again.

In my opinion an upper-case emails should not be a cause for complain (unless there are some details I am unaware of). 

PS: Thank you very much for developing this very useful extension!

**Comment by ia0** [comment]
Fixed upstream.

**Comment by Vuizur** [comment]
Awesome, thanks!

Dne st 13. 9. 2023 18:49 uživatel Julien Cretin ***@***.***>
napsal:
