### ISSUE TITLE
VSCode settings needs extension reload to be applied

### ISSUE THREAD

**Issue by echoix** [tamasfe/taplo#375]
I wasn't able to configure the settings for the VSCode extensions.

I was trying all the options one by one, and never I had a different output. I was in a GitHub codespaces, so I switched back to a local-only setup, and same thing, I wasn't able to have formatting settings applied. I made sure to set a different string to the indent string between tests.

I wanted to at least have some indented entries for a hugo config.toml. I tried out by installing other older versions to see if any version of the extension has ever worked. And yes! But also the new one. The key was by installing an older version, it needed a reload, and the reload was what it took to have the settings applied. 

So I suppose that the default state when installing the extension, that is, formatting the file real flat, (nothing is indented, all spaces/tabs removed at the beginning of lines), was only since is there is no key for "evenBetterToml.formatter.indentString" in the `settings.json`, the empty textbox in the UI means "", (an empty string).

![image](https://user-images.githubusercontent.com/27212526/215295371-96f67e77-69fc-46f6-b75a-c9498d14dd15.png)
![image](https://user-images.githubusercontent.com/27212526/215295383-f6b4bc2f-df16-4da5-8b90-0a7b0355b2f2.png)
![image](https://user-images.githubusercontent.com/27212526/215295389-fa01be06-deae-4210-aed1-2af3ee344f63.png)

This is when the setting is reset:
![image](https://user-images.githubusercontent.com/27212526/215295400-71658ff0-4191-4405-9d7e-0ff38f5b62d5.png)

**Comment by davidtorosyan** [comment]
+1, just spent a bunch of time trying to figure out why my changes to `taplo.toml` weren't working.

Could we maybe add a note to the extension README, in the configuration file section? I don't mind reloading, but it would be good to know it's needed.

**Comment by ZhiliangWu** [comment]
Yes, it would be great if it's at least mentioned in README.

**Comment by ia0** [comment]
Thanks for the diagnosis! However this project is only passively maintained. Feel free to open a PR with the appropriate suggested change in the README regarding the mentioned documentation issue. I'll review and approve or comment it. Thanks again!
