### ISSUE TITLE
Unstable cargo features not supported by the vscode extension

### ISSUE THREAD

**Issue by figsoda** [tamasfe/taplo#38]
Cargo nightly has [unstable features](https://doc.rust-lang.org/cargo/reference/unstable.html), and they don't seem to be supported by the vscode extension

<br />

For example, in my case, after enabling the [profile `strip` option](https://doc.rust-lang.org/cargo/reference/unstable.html#profile-strip-option) with
```toml
cargo-features = ["strip"]
```

<br />

The following code block still emits an error `unknown property Even Better TOML (Profile)` pointing at `strip`
```toml
[profile.release]
strip = "symbols"
```

<br />

Here's a screenshot of the error
![screenshot](https://user-images.githubusercontent.com/40620903/92803311-4d38f600-f385-11ea-8e44-d6a07d48d613.png)

**Comment by tamasfe** [comment]
I don't think I'd like to include unstable features in the schema, as they might come and go, and would be hard for me to keep in sync.

Instead the schema allows unknown keys for now.
