### ISSUE TITLE
fly.io schema is outdated

### ISSUE THREAD

**Issue by mootari** [tamasfe/taplo#398]
It seems that the [fly.io schema](https://github.com/tamasfe/taplo/blob/ccf23c655111e4feab2f55b993f65175120fbac3/site/site/public/schemas/fly.toml.json) is out of date, as sections like [`[http_service]`](https://fly.io/docs/reference/configuration/#the-http_service-section) are missing.

What is the current process to update the schema? I assume the definition was originally generated via schema-gen (which has been removed since)?

**Comment by mootari** [comment]
The flyctl repo contains a test file with the promising name [full-reference.toml](https://github.com/superfly/flyctl/blob/bebde8ca52aad7a63ea795b4b5a4a141713f6feb/internal/appconfig/testdata/full-reference.toml#L88) which unfortunately lacks types.

On the other hand, [appconfig/config.go](https://github.com/superfly/flyctl/blob/bebde8ca52aad7a63ea795b4b5a4a141713f6feb/internal/appconfig/config.go) and related files define types and keys, but I'm not sure how parsable they are.

Do your schema definitions follow a specific standard?

**Comment by panekj** [comment]
Schemas are provided via SchemaStore so if there is anything outdated, it should be reported in https://github.com/schemastore/schemastore
