### ISSUE TITLE
Extension has absurdly high resource usage

### ISSUE THREAD

**Issue by LJNeon** [tamasfe/taplo#40]
I'm connecting to a VPS using the VSCode remote extension, and this extension has to be installed on the VPS to work. But when I do that, my VPS is maxed at 100% CPU and memory usage (cpu never goes above 5% normally, and memory is never higher than 20%). Uninstalling the extension instantly fixes the resource usage and installing it again makes the usage quickly return, so I'm fairly certain this extension is the cause. This is definitely a low-end VPS, but this still seems absurd.

**Comment by LJNeon** [comment]
I've also noticed that a very significant amount (nearly 1 GB/s) of reads from disk are being done (only when this extension is installed, vanishes the moment I uninstall), which is rather confusing.

**Comment by LJNeon** [comment]
For context, I have very few TOML files, none of which are large whatsoever, and only one of which was ever opened in VSCode.

**Comment by tamasfe** [comment]
Could you please do the following:

- See if the behaviour is similar in a local environment for the same TOML file and workspace
- Disable schemas with the setting `"evenBetterToml.schema.enabled": false`

The extension is far from being optimized but this seems very unreasonable, especially the disk reads since it doesn't do any i/o at all itself.

**Comment by LJNeon** [comment]
I'm unable to reproduce this in a local environment, even considering the local environment having better specs. Also, disabling schemas doesn't seem to affect resource usage noticeably.

**Comment by tamasfe** [comment]
I cannot seem to reproduce it on my VPS, just creating an empty directory with a sample `Cargo.toml` in it. Although it isn't a low-end VPS.

Is your workspace large by any means? Even if the extension isn't doing i/o, as far as I remember it does tell VSCode to watch for all `.toml` files.

**Comment by LJNeon** [comment]
There's maybe 100 files total, out of which not even 10 are `.toml` files. I've continued testing and it appears that this problem happens sometimes even with your extension uninstalled, but every time with it installed. Which makes me think it's more likely a VSCode issue somehow.

**Comment by tamasfe** [comment]
VSCode is rather resource-hungry even without extensions, so I wouldn't be surprised if it could be noticed on a low-end VPS.

The extension itself doesn't do any work after it parses the TOML file without further user input. So if you see TOML syntax errors and such, you can be sure that the current workload is done. Unless it's an endless loop in the parser, which has happened in the past and is obviously a bug, but at that point it becomes unresponsive and easy to spot.

I cannot seem reproduce anything about this issue, but I'll leave this open in case you find something.

**Comment by LJNeon** [comment]
Yea, this is very unlikely to be a problem with your extension. My best guess is that the extension somehow triggers a vscode remote extension bug, but the bug sometimes occurs regardless. I'll go ahead and close this.
