### ISSUE TITLE
Smarter "align_comments" when there's only 1 comment?

### ISSUE THREAD

**Issue by thejcannon** [tamasfe/taplo#404]
:wave: Howdy!

We've added support for Taplo to https://github.com/pantsbuild/pants, and are not integrating it into the repo itself.

One thing I noticed was I like the idea of "align_comments" (:+1:) but I wished that if there was 1 (and only 1) comment, it didn't apply.

E.g.
```toml
foo = [
    "hello world",
    "a",                # I'm way over here
    "b",
]
```
would be:
```toml
foo = [
    "hello world",
    "a",  # I'm way over here
    "b",
]
```

but adding a new comment would result in
```toml
foo = [
    "hello world",
    "a",                # I'm way over here
    "b",                # me too
]
```

This, of course, would be hidden behind a toggle.

Thanks again (I'm also looking forward to integrating Taplo into our eventual Pants LSP for handling our config file, so thanks for the LSP side of things too :raised_hands: )

**Comment by ia0** [comment]
Hi @thejcannon and thanks for the suggestion!

Given the project is currently under-staffed (see #403) and this feature is rather low priority at the moment, I would not expect a PR in the next months about this. However, if you are ready to write the PR yourself, I would be happy to review it.

**Comment by thejcannon** [comment]
I took a stab at it :smile:
