### ISSUE TITLE
Is "migrations" a reserved word or something?

### ISSUE THREAD

**Issue by rafamerlin** [tamasfe/taplo#413]
I bumped into this one accidentally but seems to be very easy to reproduce.

run `cargo new --bin migrations` and open this new folder in vscode, when you add any dependency you will get this error (adding tokio for example):

```
[{
	"resource": "/home/me/dev/rust-tests/migrations/Cargo.toml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Additional properties are not allowed ('tokio' was unexpected)",
	"source": "Even Better TOML",
	"startLineNumber": 8,
	"startColumn": 2,
	"endLineNumber": 8,
	"endColumn": 14
}]
```

Here's an image of it:
![image](https://github.com/tamasfe/taplo/assets/11574755/621e9c59-fa7e-4e9c-9c3c-f568610e03ab)

If I rename the folder to migration instead of migrations the issue goes away for example, so seems to be specific to migrations, the project builds and runs fine even with the error if I keep it named migrations

![image](https://github.com/tamasfe/taplo/assets/11574755/36ac63d6-cf78-476a-a3e4-969128a6fdbc)

**Comment by ia0** [comment]
Thanks for the bug report! I'm able to reproduce. I suspect this is related to https://github.com/SchemaStore/schemastore/issues/3021.

I think the next step is to figure out which schema is used. I suspect that the wrong one is used because of the file path matching another rule. However I don't know how to print the used schema, I'll have to investigate (this weekend at the earliest).

**Comment by ia0** [comment]
Actually using `RUST_LOG=debug` works:

```
  2023-06-20T22:10:12.417075Z DEBUG taplo_common::schema: failed to cache schema, error: cache path not set
    at crates/taplo-common/src/schema/mod.rs:211
    in taplo_common::schema::load_schema with schema_url=https://json.schemastore.org/drupal-migration.json
    in taplo_common::schema::validate with schema_url=https://json.schemastore.org/drupal-migration.json
    in taplo_common::schema::validate_root with schema_url=https://json.schemastore.org/drupal-migration.json
    in taplo_cli::commands::lint::lint_files
    in taplo::taplo
```

So for some reason it's using the drupal-migration schema...

**Comment by ia0** [comment]
Ok so the bug is in taplo, in particular the `SchemaCatalog::transform_paths()` function that replaces the extensions with toml, which means that the `**/migrations/*.yml` rule from Drupal Migration becomes `**/migrations/*.toml`. I don't know why this code exists. I would suggest removing it.

**Comment by rafamerlin** [comment]
Thanks a lot for looking into this. I didn't notice the notifications, sorry for not replying earlier.
