### ISSUE TITLE
Feature Request: Sorting TOML

### ISSUE THREAD

**Issue by Eutropios** [tamasfe/taplo#421]
Hello! I'd like to request a feature in which a user is able to highlight text within a code block and then sort it.
Ex:
```toml
[tool.ruff]
line-length = 88
show-fixes = true
select = [
    "F",
    "E",
    "W",
    "C90",
    "N",
    "D",
    "UP",
    "ANN"
]
```
The contents of the array should be sorted alphabetically.

**Comment by ia0** [comment]
I'm not sure I understand what you mean by "highlight", but would using the following `taplo.toml` fix your issue?

```toml
[formatting]
reorder_arrays = true
```

**Comment by Eutropios** [comment]
By highlight I meant select, my apologies. But yes, this very much helps with my issue. I appreciate the help. :D
