### ISSUE TITLE
Is possible to disable table indent?

### ISSUE THREAD

**Issue by AurevoirXavier** [tamasfe/taplo#423]
```
[notification]
	[notification.mail]
```

I want it to be

```
[notification]
[notification.mail]
```

**Comment by ia0** [comment]
I can't reproduce. Could you provide reproduction steps? Here is what I tried:

- Create a file called `foo.toml` with the following content:
    ```toml
    [notification]
    [notification.mail]
    ```
- Run `taplo format foo.toml`
- Observe that the file is still the same
- Indent `[notification.mail]` with 2 spaces
- Run `taplo format foo.toml`
- Observe that the indentation was removed

**Comment by AurevoirXavier** [comment]
> I can't reproduce. Could you provide reproduction steps? Here is what I tried:
> 
> * Create a file called `foo.toml` with the following content:
>   ```toml
>   [notification]
>   [notification.mail]
>   ```
> * Run `taplo format foo.toml`
> * Observe that the file is still the same
> * Indent `[notification.mail]` with 2 spaces
> * Run `taplo format foo.toml`
> * Observe that the indentation was removed

Actually, I am not sure why it is not working in my VSCODE. Despite changing the configuration multiple times, it still does not work.

**Comment by AurevoirXavier** [comment]
It looks like it was broken during some updates. I have used this for few years.

A compeletely fresh reinstall solved this.

**Comment by AurevoirXavier** [comment]
I found the root cause. I don't why this plugin can not hot reload now. After I change the configurations I need to close and reopen the whole editor to apply the latest configurations.

Is this expected?

**Comment by ia0** [comment]
I don't know about VS Code, but the taplo LSP server loads the config during initialization and I don't think it rereads it when modified. Maybe VS Code was restarting the LSP server when the config file was changed.
