### ISSUE TITLE
[VS Code extension] Almost everything is red

### ISSUE THREAD

**Issue by rafrafek** [tamasfe/taplo#435]
Hello,
is there a way to specify the toml syntax highlighting default color to something other than bright red?

I'm using the default VS Code light theme "Light Modern".

<img width="393" alt="image" src="https://github.com/tamasfe/taplo/assets/23004737/438eb864-ec7b-49f8-9695-ad557eaab1d1">

Thanks!

**Comment by ia0** [comment]
I'm not familiar with VS Code, but I don't think this is related to Taplo itself. It's probably a syntax highlighting configuration in VS Code. At least that's how it works in Emacs. Did you try to disable Taplo to see if you get the same syntax coloring?

**Comment by rafrafek** [comment]
VS Code does not support toml files. This is why I installed `tamasfe.even-better-toml` extension. Without the extension there is no syntax coloring at all. With the extension colors appear. When using dark theme colors match other (supported by default) formats like yaml and json, but when using light theme everything in toml file is red. This does not match colors in other files. I believe there is something set in extension itself that forces the colors to be red.

**Comment by ia0** [comment]
I see. Then it's probably a part specific to VS Code then, which I'm not familiar with, so not able to help with.

**Comment by panekj** [comment]
https://github.com/tamasfe/taplo/tree/master/editors/vscode#additional-syntax-colors

**Comment by rafrafek** [comment]
Thanks! It works!

My `settings.json`:
```json
{
    "editor.tokenColorCustomizations": {
        "[*Light*]": {
            "textMateRules": [
                {
                    "scope": "support.type.property-name.toml",
                    "settings": {
                        "foreground": "#0451A5"
                    }
                },
                {
                    "scope": "support.type.property-name.array.toml",
                    "settings": {
                        "foreground": "#0451A5"
                    }
                },
                {
                    "scope": "support.type.property-name.table.toml",
                    "settings": {
                        "foreground": "#0451A5"
                    }
                }
            ]
        }
    }
}
```

Result:

<img width="371" alt="image" src="https://github.com/tamasfe/taplo/assets/23004737/43318813-1c6f-4144-adbd-4f258452aa88">

And thanks to `"[*Light*]"` it is not applied when using dark theme:

<img width="376" alt="image" src="https://github.com/tamasfe/taplo/assets/23004737/a4564464-78a1-44e0-8875-d6ad7f8f4920">

I have auto dark theme in my OS and VS Code is set to sync light/dark theme with the OS, so I use light theme during the day and dark theme after the sunset. Now it works perfectly! Thanks!
