### ISSUE TITLE
vscode extension still marked as "Preview" even though Better TOML is now deprecated

### ISSUE THREAD

**Issue by jmhodges** [tamasfe/taplo#436]
The "Better TOML" vscode extension has marked itself as "deprecated" and directed users to this one. However, this vscode extension still claims its in "Preview".

So, I'm a little confused. Is this one stable or is the other one deprecated?

Thanks so much for your work!

**Comment by panekj** [comment]
> Is this one stable or is the other one deprecated?

We don't manage the other extension so the status it has doesn't relate to status of our extension.
Generally we try to not break anything between releases but it might be happen, other than that, our extension should work fine.

**Comment by tamasfe** [comment]
The extension is currently stuck in a limbo of being generally stable and usable for most use-cases but not being in a state that I would proudly call a finished product as it is riddled with bugs and questionable architectural decisions, so despite being out there for quite a while, I did not remove the `preview` label.

I guess it will stay in `preview` forever or until someone decides to pick it up and rework/fix the parts that need it, so far no one seems to think that additional development would be worth the effort and time investment (myself included).

**Comment by jmhodges** [comment]
Thanks for the response!

Out of curiosity, do y'all have a list of must-fix-first tickets?

**Comment by ia0** [comment]
> Out of curiosity, do y'all have a list of must-fix-first tickets?

Good question. Issues are not really tagged as they used to be in the past. I'll try to tag the most recent ones. But if you want to help and write PRs, I would suggest to look at the most recent issues first since it should be easier to get feedback.

**Comment by ia0** [comment]
@jmhodges if you want to help and since you seem to use VSCode, the most important issue that needs help is #434. It's currently blocking the release of 0.19.1 (rolled back to 0.19.0 in 0.19.2) which fixes multiple issues.

I'm closing this issue since the status of Even Better TOML is not related to Better TOML being deprecated. The Preview marker will be removed when Even Better TOML is ready, independently of this issue.
