### ISSUE TITLE
even better toml: Disable long lines being split across multiple lines

### ISSUE THREAD

**Issue by rukai** [tamasfe/taplo#437]
Is there a way to disable long lines being split into multiple shorter lines?

Lines like this:
![image](https://github.com/tamasfe/taplo/assets/5120858/0b33803f-d6c9-40c9-8da0-01d6e381c426)

Are being formatted like this:
![image](https://github.com/tamasfe/taplo/assets/5120858/9febb6e9-c5bf-4b30-b5f2-e5834b9a6455)

Normally I'm not so fussed how my editor decides to format things, but when I'm making a PR to an open source project I dont want to mess with the authors formatting. So I would personally rather this be always be disabled for me.

Currently I'm working around this with "save without formatting" but my muscle memory often betrays me.

**Comment by rukai** [comment]
Hmmm, now that I look further at this, I probably just want a way to disable formatting of toml entirely which I can do with this https://stackoverflow.com/questions/44831313/how-to-exclude-file-extensions-and-languages-from-format-on-save-in-vscode

I think I probably prefer my deps to take up one line even if its really long, but in the end I really dont feel strongly about toml formatting.
Sorry to bother you.

**Comment by panekj** [comment]
There are `Array Auto Expand` and `Column Width` options in settings that can be changed to customise that behaviour.
![image](https://github.com/tamasfe/taplo/assets/50457605/d674f7a2-919c-48f4-ac74-76b81384dcdc)
