### ISSUE TITLE
Option to disable formatting for templated TOML files

### ISSUE THREAD

**Issue by mr-karan** [tamasfe/taplo#459]
I've Go templating in my `.tpl.toml` files:

```
log_level = "debug"
{{- range nomadService "app" }}
url="http://{{ .Address }}:{{ .Port }}"
{{- end }}
queries_file = "queries.sql"
```

On invoking the formatter, it completely destroys the templating logic:

```

{{- range nomadService "app" }}

{{- end }}
log_level = "debug"
url = "http://{{ .Address }}:{{ .Port }}"
queries_file = "queries.sql"
```

I couldn't find a way to disable formatting for a specific set of file extension (in this case *.tpl.toml). Is it possible to make it configurable to opt out of formatting for certain file extensions?

**Comment by ia0** [comment]
Yes, you can create a `taplo.toml` file as described [here](https://taplo.tamasfe.dev/configuration/file.html#exclude):

```toml
exclude = ["**/*.tpl.toml"]
```

**Comment by mr-karan** [comment]
Thanks!

Apologies, I didn't include in my OP that I couldn't find a native vscode setting to control this behavior. Will close this issue as it solves but it would be nice to have formatting enabled/disabled inside the vscode extension setting as well :)
