### ISSUE TITLE
Crates.io releases past 1.0.0-alpha.1 missing in Git history here?

### ISSUE THREAD

**Issue by ErichDonGubler** [tamasfe/taplo#47]
Hey there! I'm currently using `1.0.0-alpha.6` to implement some CI tooling in a closed-source project, and I noticed that there seems to be no history in this repo containing releases marked in a `Cargo.toml` file beyond the `1.0.0-alpha.1` release. Is this just something still on somebody's local machine? It seems sort of unlikely, since options like `allowed_blank_lines` is now in `master`, yet not in a Crates.io release, and `taplo/Cargo.toml` is still set to `1.0.0-alpha.1`.

**Comment by kkiyama117** [comment]
@ErichDonGubler 
I had similar probrem and found changing dependency to this git repo like `taplo  = { git = "https://github.com/tamasfe/taplo.git", features = ["serde", "verify"] }` has an effort . I don't know @tamasfe will release new one or has no plan to do so, but you can use it instead of Crates.io's one until waiting his reply.

**Comment by tamasfe** [comment]
I don't have time to design and provide a consistent API for the library right now, so I decided not to update it on crates, as the versions would be inconsistent and might contain breaking changes.

I would recommend using the master branch like @kkiyama117 said for now, this is what is used in the VSCode extension as well, so it works, and won't contain unfinished/broken code *intentionally*.

I will eventually yank the current `1.0.0-alpha.x` releases on crates, and start over with `0.1.0`, as I have many plans for this library before it reaches `1.0.0`.

**Comment by tamasfe** [comment]
@ErichDonGubler I've just published `0.2.1` which should be a major improvement over all previous releases, and I'll follow a proper `0.x.x` scheme until the library is ready for `1.0.0` from now on.
