### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ia0** [tamasfe/taplo#473]
#449 and #462 are fixing important issues and need to be released. There are other minor changes since the last release.

Before releasing, we should also bump `json_value_merge` to 2.0.0 (and update the code accordingly) because 1.2.0 was a breaking change.

**Comment by ia0** [comment]
I created #474 for the `json_value_merge` issue.

**Comment by panekj** [comment]
> It would be great because [CI fails](https://github.com/lifescapegame/lifescape/actions/runs/6147934293/job/16680499099?pr=191) for me when I trying to install Taplo.

You should always use `--locked` flag when installing with `cargo install`

**Comment by Shatur** [comment]
I would like to always install the latest version.

**Comment by ia0** [comment]
The problem here is that you can't install with `--locked` in nightly because you need #449 (`proc-macro` issue) and you can't install without `--locked` because you need #474 (`json_value_merge` issue). So right now if you want to install Taplo in CI you need to install with stable and `--locked` or from git if you use nightly. This is a considerable issue we are aware of and a release is needed for many other reasons.

@tamasfe Do you think you would have time for a release? On my side, I'm not sure I do. @panekj what about you?

**Comment by David-Else** [comment]
I hope the full language server version can be released via NPM too rather than the rather useless version that is currently there. Cheers :)

**Comment by panekj** [comment]
> what about you?

I'll take a look at the process tonight but nothing promised.

**Comment by flying-sheep** [comment]
Are you making any headway with this? There’s now multiple bugfixes to CLI and extension that I’m waiting for.

**Comment by ia0** [comment]
Would be nice to have #496 merged before the release, such that we also produce builds for ARM.

**Comment by flying-sheep** [comment]
Eventually, you might want to switch to https://release-plz.ieni.dev/ which automates a lot of things.

**Comment by JounQin** [comment]
The npm package is also very outdated #480

**Comment by o-az** [comment]
If anyone's interested in forking this and maintaining it with me let me know.

**Comment by JounQin** [comment]
I've forked it at https://github.com/unrs/taplo but isn't not sure to publish it.

**Comment by ia0** [comment]
Feel free to also volunteer at [maintaining this crate](https://github.com/tamasfe/taplo/issues/403). That's probably the most natural way to start contributing. You would be able to fork later if something is limiting you.

If you nevertheless want to fork, which I would understand if you are planning to invest significant effort refactoring, I would suggest contacting @tamasfe to discuss the best way to proceed:
- Should the name of the project be different?
- Should it have a link from the README of this project?
- How should it preserve existing contribution authorship?
- Should it be under an organisation or a specific user?
- etc

Note that I will most probably step down from maintaining this crate in the coming months (baby is coming so I'll have much less time). Also there's too much Javascript and VS Code related issues in this project which is far from my expertise and my taste.

**Comment by JounQin** [comment]
@ia0 See https://github.com/tamasfe/taplo/issues/403#issuecomment-1828235877

**Comment by panekj** [comment]
> See [#403 (comment)](https://github.com/tamasfe/taplo/issues/403#issuecomment-1828235877)

As I mentioned I'm strongly against any kind of permission transferring, mainly due to security concerns, and a much better alternative would be to grant more contributors access here or you can fork the project.

As for my availability I'm slowly finishing a project at work that took waaaay too much of my time and mental capacity over past year and will have very long holidays time which should let me re-focus on FOSS projects. (I also stepped down from maintenance commitments in other major project)

**Comment by ia0** [comment]
The decision of permission transferring is up to @tamasfe anyway, similarly to be added as a contributor. So I guess the next step is to wait to get @tamasfe 's opinion on the matter. An absence of response (say after 1 or 2 months) would mean that forking the project is the best course of action. And in that case I think it should have a new name (because of crates.io but also to avoid transparent trust transfer as @panekj mentioned).

**Comment by JounQin** [comment]
@ia0 @panekj 

I'm also a maintainer of many influential projects like https://github.com/prettier/prettier-eslint, https://github.com/prettier/eslint-plugin-prettier, https://github.com/prettier/pretty-quick, etc.

I understand how difficult to be trusted as a new maintainer and how difficult to be qualified maintainer, and also forking is always not the best solution which will hurt the community brand. But I still hope I can offer some help here. What is the main blocking now? Can I help rasing a PR for it?


Again, I'm very new to Rust community, but I still think we can work together.


cc @tamasfe

**Comment by ia0** [comment]
> What is the main blocking now?

I'd say going over all PRs since last release to update the changelogs and the version numbers, such that @tamasfe can just release it. Ideally also test VS Code because that was the problem last time.

**Comment by JounQin** [comment]
@ia0 If you have permission to invite me as collerbotator, I'd like to help installing some automatic tools which I'm very familiar to use and easy to maintain.

**Comment by ia0** [comment]
> So you don't have the permission to release?

No. And I don't think I can add you either. I'm also going offline for 2 weeks now. The tooling to use would probably be something to discuss.

**Comment by JounQin** [comment]
> > So you don't have the permission to release?
> 
> 
> 
> No. And I don't think I can add you either. I'm also going offline for 2 weeks now. The tooling to use would probably be something to discuss.

OK, I think I'll have to maintain the fork instead.

Do you want to join @unrs org or https://github.com/unrs/taplo repo?

**Comment by o-az** [comment]
> I've forked it at https://github.com/unrs/taplo but isn't sure to publish it.

@JounQin in my opinion you should rename it to something else otherwise people will not find your fork easily as the current one will always show first.

**Comment by JounQin** [comment]
@o-az We don't need to fork now since after https://github.com/tamasfe/taplo/issues/403#issuecomment-1913342635, I'm proud to be a collaborator of this project! ❤️

**Comment by lorepozo** [comment]
@JounQin a new version hasn't been released for the VSCode extension — would you be able to push a new version there? In the meantime, I'm still getting panics from #434 (using custom json schema, whether by `#:schema file.json` line or by vscode extension settings) that should be resolved by #462

**Comment by nevir** [comment]
Following up on this as well - any chance of a new VS Code extension release?

**Comment by panekj** [comment]
> Following up on this as well - any chance of a new VS Code extension release?

If I'll fix the issues I'm having then maybe
