### ISSUE TITLE
Tables plus dotted keys generates incorrect error (vscode extension)

### ISSUE THREAD

**Issue by alexferro** [tamasfe/taplo#48]
I am running version 0.8.7 as reported in vscode and listed at time of writing as the up to date version on the vscode marketplace.
I am running VSCode 1.50.1 on Windows 10 x64.

If I mix both fully qualified table syntax and table plus dotted key syntax, the "Even Better TOML" extension appears to incorrectly give me a duplicate table definition error if the first subtable matches a top level table name. 
While there is no explicit sentence that I can find in the TOML spec, either rc1, or (current) rc3, stating it's not an error, the spec does appear to specify (and the code appears to handle this in isolation) that dotted keys under a table definition append under that table, not the global scope, and thus I would expect the intended result would not have it error about a conflict with a global table. Especially since using a dotted table definition works as expected.
TOML [https://toml.io/en/v1.0.0-rc.3#table](v1.0.0.-rc.3) has an explicit example of dotted keys inside a table, and the example is the same in [https://toml.io/en/v1.0.0-rc.1#table](v1.0.0.-rc.1).

Hopefully, these examples make it clear what the issue is.

Invalid per the extension:
```toml
[foo]
bar = 1

[baz]
foo.bar = 2 # Not Ok per the extension, conflicts with table "foo"

[bar.foo] # Ok
baz = 3
```
Expected JSON Tree:
```json
{
  "foo": {
    "bar": 1
  },
  "baz": {
    "foo": {
      "bar": 2
    }
  },
  "bar": {
    "foo": {
      "baz": 3
    }
  }
}
```

Do note that if I copy just the middle TOML snippet:
```toml
[baz]
foo.bar = 2
```
as JSON, the contents of my clipboard are the expected:
```json
{
  "baz": {
    "foo": {
      "bar": 2
    }
  }
}
```

**Comment by tamasfe** [comment]
Thanks for the bug report!

I've just finished refactoring most of the parsing code that fixes several bugs like this one, I expect to publish a new version of the extension this week.

**Comment by alexferro** [comment]
And thank you for the prompt response. Once I figured out what was happening enough to write the bug report, it really is only a minor issue for my use case.

I look forward to the update, when ever it comes out, but it's a low priority on my list.
