### ISSUE TITLE
NPM package is not up-to-date

### ISSUE THREAD

**Issue by so1ve** [tamasfe/taplo#480]
On NPM: https://www.npmjs.com/package/@taplo/lib, the latest version is `0.4.0-alpha.2`, which is published one year ago;
On crates.io: https://crates.io/crates/taplo, the latest version is `0.12.1`, which is published 3 months ago.

**Comment by s-weigand** [comment]
`@taplo/cli` is also outdated:
- [npmjs.com](https://www.npmjs.com/package/@taplo/cli): `0.5.2` (a year ago)
- [crates.io](https://crates.io/crates/taplo-cli): `0.8.1` (4 months ago)
