### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by baboon-king** [tamasfe/taplo#488]
What are these? I just created a simple file. I did not see any relevant information in the document

![image](https://github.com/tamasfe/taplo/assets/63645337/9fe0436a-9cdd-4092-8112-cb89a8b981ca)

```
"author" is a required propertyEven Better TOML
"config" is a required propertyEven Better TOML
"createAt" is a required propertyEven Better TOML
"homepage" is a required propertyEven Better TOML
"identifier" is a required propertyEven Better TOML
"meta" is a required propertyEven Better TOML
"schemaVersion" is a required propertyEven Better TOML
```

**Comment by ia0** [comment]
Please provide the file content. I cannot reproduce with just the first 2 lines. This is probably just because some required fields are missing. If not, then that's probably a schema mismatch.

**Comment by baboon-king** [comment]
Sorry, I should have provided detailed information. But when I revalidated my computer today, this issue no longer occurred. This should be an unexpected error, I have decided to close this issue

**Comment by ia0** [comment]
Thanks for the feedback! It might also be a transient error with the schema store. Feel free to open a new issue in case you experience the problem again.
