### ISSUE TITLE
Can not install with cargo

### ISSUE THREAD

**Issue by lemunozm** [tamasfe/taplo#507]
Hi! 

Following the web instruction to install taplo as follows:
```sh
cargo install taplo-cli --locked
```

I have a compilation error during the process. I'm using cargo `1.75.0-nightly`. Any idea?

**Comment by ia0** [comment]
Thanks for the report! This looks like a duplicate of #490 and is waiting #473 to be fixed.

You can install from git in the meantime: `cargo install --git=https://github.com/tamasfe/taplo.git taplo-cli`

**Comment by lemunozm** [comment]
Thanks so much for your fast response!
