### ISSUE TITLE
VS Code extension validates against an outdated version of a local schema

### ISSUE THREAD

**Issue by TheOnlyTails** [tamasfe/taplo#508]
I have a file structure like this: 
```
|- schemas/generated
|   |- word.json
|- words
    |- a.toml
    |- aka.toml
    |- akesi.toml
    |- ... 
```

And I added this line to the `a.toml` file:
```toml
"$schema" = "../schemas/generated/word.json"
```

Afterward, I noticed my TOML file didn't actually fit the JSON schema that was generated, so I edited the schema to fit it, but the Even Better TOML extension keeps reporting a schema error, as if it's still checking against the old version of the schema.

Why is this happening? Does the extension keep a cache of schemas?

**Comment by ia0** [comment]
This is a known issue. Closing as a duplicate of #347.
