### ISSUE TITLE
Inconsistent alphabetical ordering of table entries

### ISSUE THREAD

**Issue by IttayWeiss** [tamasfe/taplo#511]
The toml snippet: 
'''
    a = { t = true }
    a- = { t = true }

    b-.t = true
    b.t = true
'''
shows the inconsistency. Semantically, there is no difference between s = { t = true } and s.t = true, so the two groups should be ordered in the same way. The alphabetical ordering should be by field name, and not by the string preceding the '='.

**Comment by ia0** [comment]
Thanks for the bug report! I can reproduce.

The project is passively maintained which means this will only get fixed if someone writes a PR. The sorting code needs some cleanup by using a helper function do transform the key for sorting. That cleanup function could suffix a dot. That should fix this issue.
