### ISSUE TITLE
Missing "unstable_features" property in makefile.toml.json schema

### ISSUE THREAD

**Issue by ddnomad** [tamasfe/taplo#517]
[Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) that relies on Taplo for linting is complaining about an unexpected key in [Cargo Make](https://github.com/sagiegurari/cargo-make) configuration files that look like the following:

```toml
[config]
unstable_features = ["CTRL_C_HANDLING"]
```

The exact error is `Additional properties are not allowed ('unstable_features' was unexpected)`.

This seems to be because `unstable_features` property is missing from the schema in `site/site/public/schemas/makefile.toml.json`.

The fix should be fairly easy and I can handle this if the maintainer is okay with that. As part of this, I guess it is worth going through at least the rest of the `config` section schema and make sure it is matching [Cargo Make's docs](https://sagiegurari.github.io/cargo-make/api/cli/types/struct.ConfigSection.html).

Do let me know.

**Comment by ia0** [comment]
Thanks a lot for volunteering to fix this! However, the fix should be done in https://github.com/SchemaStore/schemastore instead since Taplo uses that. The schemas in this repository are not used anymore.

**Comment by ddnomad** [comment]
> Thanks a lot for volunteering to fix this! However, the fix should be done in https://github.com/SchemaStore/schemastore instead since Taplo uses that. The schemas in this repository are not used anymore.

Ah, thanks for letting me know @ia0, do appreciate it. I'll close this issue then and go report it to [SchemaStore/schemastore](https://github.com/SchemaStore/schemastore) instead.
