### ISSUE TITLE
pdm scripts give errors with the help option in pyproject.toml

### ISSUE THREAD

**Issue by ShaiAvr** [tamasfe/taplo#519]
I am working on a Python library that uses the `pyproject.toml` configuration file and the [pdm](https://pdm-project.org/latest/) build system. I have some custom `pdm` scripts as explained [here](https://pdm-project.org/latest/usage/scripts/). I wanted to add a `help` option to document my scripts (see [here](https://pdm-project.org/latest/usage/scripts/#show-the-list-of-scripts)), but it causes the extension to complain that `{"cmd":"...","help":"..."} is not valid under any of the given schemas`. I tried both with the following:
```toml
[tool.pdm.scripts]
test.cmd = "..."
test.help = "..."
```
and:
```toml
[tool.pdm.scripts]
test = { cmd = "...", help = "..." }
```
Both cases gave me the same error. Removing the `help` option in either case solves the error. I tried to use the PyProject schema from the JSON Schema Store:
```json
"evenBetterToml.schema.associations": {
	"^pyproject\\.toml$": "https://json.schemastore.org/pyproject.json"
}
```
but it still gave me the same error.

And just to be clear, the scripts work as intended. Running `pdm run test` runs the script and running `pdm run --list` shows the script with the description of the help option. It's a false error from Even Better TOML.

**Comment by ia0** [comment]
Thanks for the issue. This is a schema issue, not a Taplo issue. And it actually has been fixed 4 days ago: https://github.com/SchemaStore/schemastore/pull/3480. If you try again it should work now.
