### ISSUE TITLE
Error that is not "expected identifier"

### ISSUE THREAD

**Issue by MrAmericanMike** [tamasfe/taplo#520]
The error reports as: `expected identifier`

![image](https://github.com/tamasfe/taplo/assets/8037559/ac4e6a56-cf34-4324-bfe1-a73d623ff823)

Apparently this is not supposed to error as the syntax is valid.

**Comment by ia0** [comment]
This is working as intended. Bare keys can only contain letters, digits, dash, and underscore: https://toml.io/en/v1.0.0#keys. You probably meant to write:

```toml
[[dependencies."${mod_id}"]]
modId = "forge"
```

**Comment by MrAmericanMike** [comment]
> This is working as intended. Bare keys can only contain letters, digits, dash, and underscore: https://toml.io/en/v1.0.0#keys. You probably meant to write:
> 
> ```toml
> [[dependencies."${mod_id}"]]
> modId = "forge"
> ```

Thanks a lot, will write it like that on the file and report back to the Minecraft Forge Community, as that comes as a template on their site.
