### ISSUE TITLE
What is cache used for when you run format.

### ISSUE THREAD

**Issue by hituzi-no-sippo** [tamasfe/taplo#522]
Hi.

What is cache used for when you run `taplo format --cache-path <CACHE_PATH>` command.

I created this issue because Taplo displays `--cache-path <CACHE_PATH>` in output of `taplo format --help` command.

`help.sh`

``` bash
#!/usr/bin/env bash

wget --quiet --output-document taplo.gz https://github.com/tamasfe/taplo/releases/download/0.8.1/taplo-linux-x86_64.gz
gzip --decompress taplo.gz
chmod +x ./taplo
./taplo --version

set -x
./taplo format --help | grep --after-context=1 'CACHE_PATH'
```

Result

``` console
$ bash help.sh
taplo 0.8.1
+ ./taplo format --help
+ grep --after-context=1 CACHE_PATH
        --cache-path <CACHE_PATH>
            Set a cache path
```

System

- OS Ubuntu 20.04 LTS (WSL2)
- Version: taplo 0.8.1

Thanks.

**Comment by panekj** [comment]
`--cache-path` is used for storing schema cache, it is not used when using `taplo format` but it's part of general arguments next to `--config` and `--no-auto-config` which is why it displays in help
