### ISSUE TITLE
Allow leaving `version` field out from `[package]` 

### ISSUE THREAD

**Issue by faern** [tamasfe/taplo#530]
![screenshot_2024-01-16_14-08-02](https://github.com/tamasfe/taplo/assets/332294/b0be83e2-518a-448d-b198-3326481ad8f0)

The Even Better TOML extension for vscode gives me an error if I don't specify the version of a Cargo package. But since Rust [1.75.0 this is no longer required](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28), so my TOML is valid. I supposed the bug is in this repository, to stop treating `version` as mandatory.

**Comment by ia0** [comment]
Thanks for pointing that out! Taplo uses SchemaStore for this, so the fix would need to be there, in particular [here](https://github.com/SchemaStore/schemastore/blob/ba837335f2e054f17c3d0294424ae6f2555124e4/src/schemas/json/cargo.json#L283) I guess, but I'm not a schema expert. If you create an issue or PR in SchemaStore, feel free to link it with this issue. I'm going to close this as not planned.

**Comment by faern** [comment]
My PR was merged! And my understanding is that taplo loads the schema definitions over the web, live. So no releases needed? I tried it out, and I no longer get errors in my `version`-less crates :partying_face: Great. Thank you!

**Comment by ia0** [comment]
Thanks a lot for fixing that issue upstream!
