### ISSUE TITLE
Default Ruff configuration file reports schema error

### ISSUE THREAD

**Issue by ssteinerx** [tamasfe/taplo#536]
[Ruff config](https://docs.astral.sh/ruff/configuration/) gives a .toml file that is equivalent to the default configuration.

The error reported is:

{"quote-style":"double","indent-style":"space","skip-magic-trailing-comma":false,"line-ending":"auto","docstring-code-format":false,"docstring-code-line-length":"dynamic"} is not valid under any of the given schemas

I don't know enough about toml schema to know who's right but it seems unlikely that Ruff would provide an invalid configuration for their tool...considering what the tool is for.

**Comment by ia0** [comment]
Thanks for the issue, however this is not a problem in Taplo but in the [Ruff schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/ruff.json). I guess Ruff updated something on their side that didn't get reflected in the JSON schema. There's actually an issue is SchemaStore to link directly to the source of truth in Ruff but it seems not technically possible yet: https://github.com/SchemaStore/schemastore/issues/2731. Feel free to open an issue (or a PR) to SchemaStore and link it here for future people. I'm closing this issue.

**Comment by austinmw** [comment]
I'm still geting similar errors:

```
[tool.ruff]  # https://github.com/charliermarsh/ruff
fix = true
line-length = 100
src = ["src", "tests"]
target-version = "py311"
exclude = ["./concordia"]

[tool.ruff.lint]
ignore-init-module-imports = true
select = ["A", "ASYNC", "B", "C4", "C90", "D", "DTZ", "E", "F", "FLY", "FURB", "I", "ISC", "LOG", "N", "NPY", "PERF", "PGH", "PIE", "PL", "PT", "Q", "RET", "RUF", "RSE", "SIM", "TID", "UP", "W", "YTT"]
ignore = ["D203", "D213", "E501", "PGH002", "PGH003", "RET504", "S101", "S307"]
unfixable = ["F401", "F841"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.pydocstyle]
convention = "numpy"
```

```
{"ignore-init-module-imports":true,"select":["A","ASYNC","B","C4","C90","D","DTZ","E","F","FLY","FURB","I","ISC","LOG","N","NPY","PERF","PGH","PIE","PL","PT","Q","RET","RUF","RSE","SIM","TID","UP","W","YTT"],"ignore":["D203","D213","E501","PGH002","PGH003","RET504","S101","S307"],"unfixable":["F401","F841"],"flake8-tidy-imports":{"ban-relative-imports":"all"},"pydocstyle":{"convention":"numpy"}} is not valid under any of the given schemas Even Better TOML
```

Where's the correct place to create an issue for this?

**Comment by panekj** [comment]
> Where's the correct place to create an issue for this?

https://github.com/SchemaStore/schemastore/
