### ISSUE TITLE
`latest` release doesn't contain precompiled binaries

### ISSUE THREAD

**Issue by kziemianek** [tamasfe/taplo#542]
The links from documentation stopped working since last release.

https://taplo.tamasfe.dev/cli/installation/binary.html
example: https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz .

We switched from `latest` to `0.8.1` in order to get binaries and use them in CI. 
Is it possible to fix release so we can switch back to `latest`?

**Comment by JounQin** [comment]
Sorry about this, I'll try to fix this issue.

**Comment by kziemianek** [comment]
> Sorry about this, I'll try to fix this issue.

All good, thanks! 👍🏼

**Comment by JounQin** [comment]
Sorry, this is because the release is published manually without CI. I'm not quite sure how to re-release, I'll try to remove the tag and recreate them manually.

**Comment by JounQin** [comment]
<img width="1380" alt="image" src="https://github.com/tamasfe/taplo/assets/8336744/d6524855-4b4d-42ab-981d-ba1e9b3eafa8">

```log
[Invalid workflow file: .github/workflows/releases.yaml#L268](https://github.com/tamasfe/taplo/actions/runs/7742605055/workflow)
The workflow is not valid. .github/workflows/releases.yaml (Line: 268, Col: 19): Unrecognized named-value: 'env'. Located at position 1 within expression: env.RELEASE_VERSION .github/workflows/releases.yaml (Line: 270, Col: 19): Unrecognized named-value: 'env'. Located at position 1 within expression: env.RELEASE_VERSION
```

**Comment by tamasfe** [comment]
Seems to be https://github.com/actions/runner/issues/1189 I have no idea why/how it worked before and what changed.

**Comment by maresb** [comment]
See https://github.com/tamasfe/taplo/issues/535#issuecomment-1926446147. @nikaro writes:

> Yep, looks like the release workflow is broken: https://github.com/tamasfe/taplo/actions/runs/7742605055/workflow#L268
And it seems to be my fault 😬 the `env.RELEASE_VERSION` variable is not available in the matrix.

**Comment by nikaro** [comment]
My bad, I'm working on a PR.
