### ISSUE TITLE
Why was default-tls unconditionally enabled for reqwest?

### ISSUE THREAD

**Issue by ia0** [tamasfe/taplo#553]
I can't find the PR that merged https://github.com/tamasfe/taplo/commit/4be1d1eb9fba62ddd6cc7cf53058b6bce3d66c7c and the commit description doesn't provide a reason. @JounQin, was this pushed without PR? And what was the reason for this change? This unconditionally adds libssl3 as a dynamic library which didn't use to be the case.

**Comment by JounQin** [comment]
Because without it, it'll compile failed.

**Comment by ia0** [comment]
It's not a problem if taplo-common doesn't compile. I guess you had the issue when using publish. All of taplo-cli, taplo-lsp, and taplo-wasm provide the appropriate features to make it compile. I see 2 options:
1. Just publish with `--features=native-tls` or `--force`.
2. Add `native-tls` as a default feature and make taplo-cli and taplo-lsp depend on taplo-common with default features disabled.

We need to fix this and release a `0.9.1`.

**Comment by JounQin** [comment]
Would you like to raise a PR for it?

**Comment by ia0** [comment]
I've sent #554.
