### ISSUE TITLE
How do I get how many values there are?

### ISSUE THREAD

**Issue by manfredlotz** [tamasfe/taplo#557]
Example:

```
[[test]]
x = "something"
[[test]]
x = "hmm"
```
I would like to get the number (here = 2) of `[[test]]` occurences. How can I achieve this?

**Comment by ia0** [comment]
Taplo is not a TOML parser. For that you want something like https://crates.io/crates/toml. Taplo only formats TOML files and validates them against a schema.

**Comment by manfredlotz** [comment]
Thanks. I did misinterpret what `taplo` is providing.
