### ISSUE TITLE
doesn't work with poetry's package-mode = false

### ISSUE THREAD

**Issue by phette23** [tamasfe/taplo#558]
Poetry's pyproject.toml now supports a `package-mode = false` property of tool.poetry https://python-poetry.org/docs/master/basic-usage/#operating-modes which makes the version and name properties not required (e.g. for running an application using poetry, not writing a python library). But if you add line to `tool.poetry` and delete `name` or `version`, Even Better TOML complains that those are required properties in VS Code.

**Comment by phette23** [comment]
This is in poetry master so it's an upcoming change, not currently a problem.

**Comment by panekj** [comment]
This should be reported in https://github.com/SchemaStore/schemastore
