### ISSUE TITLE
taplo-cli 0.9.1 not released to crates.io yet

### ISSUE THREAD

**Issue by silwol** [tamasfe/taplo#559]
Hi there,

Attempting to execute `cargo install taplo-cli` in a restricted environment without an openssl-compatible library, I hit issue #554 . It appears `taplo-cli` release 0.9.1 is already tagged and fixes this problem, but not yet released to crates.io. No idea whether there is a specific process before publishing happens, or whether it's just an oversight. Creating this issue to inform you in case it's the latter.

**Comment by ia0** [comment]
This might be related to tags not being automatically created: https://github.com/tamasfe/taplo/pull/547#issuecomment-1947560805. But I just checked and it looks like the tags exist now, so maybe it's just a matter of actually doing `cargo publish`.

**Comment by silwol** [comment]
Any update on this? I'd love to introduce this into our CI where we run some alpine containers without OpenSSL, which is impossible with 0.9.0 and should be fixed with 0.9.1 iiuc. @tamasfe or @JounQin can either of you shed some light on this?

**Comment by ia0** [comment]
It seems like not only the crates were not released but also the VS Code extension. Probably the same issue.

**Comment by lucaspar** [comment]
I'm looking forward the fix for #438, which was merged back in August, but the VS Code extension hasn't been updated in almost a year. What's blocking a new release after all?

**Comment by lxl66566** [comment]
[The publish CI failed](https://github.com/tamasfe/taplo/actions/runs/9906778627/job/27369176810) to publish because taplo-cli v0.9.1 depends on taplo  v0.13.1, but for some reason the publishing of taplo v0.13.1 failed, so the highest version of taplo in crates.io is v0.13.0, that prevents taplo-cli to find the correct version.

**Comment by panekj** [comment]
https://crates.io/crates/taplo-cli/0.9.3
