### ISSUE TITLE
Syntax highlighting broken in 0.9.2

### ISSUE THREAD

**Issue by tobz1000** [tamasfe/taplo#56]
Viewing a file in 0.9.1:
![image](https://user-images.githubusercontent.com/1471978/98442025-1586ca00-20fa-11eb-9603-dd06b30da91a.png)

Viewing a file in 0.9.2:
![image](https://user-images.githubusercontent.com/1471978/98442032-1ddf0500-20fa-11eb-872e-afcfadfcd067.png)

Using VS Code 1.51.0 on Windows 10.

**Comment by tamasfe** [comment]
Thank you, sorry, I've just pushed a fix, `0.9.3` should be out [soon](https://github.com/tamasfe/taplo/runs/1367726179?check_suite_focus=true).
