### ISSUE TITLE
[LSP] Setting up schemas with SchemaStore.nvim

### ISSUE THREAD

**Issue by zyriab** [tamasfe/taplo#562]
Hi there!
First of, thanks a lot for your hard work :)

I'm using Neovim with a plugin called `SchemaStore.nvim` to provide the relevant schema from SchemaStore direstly through the LSP of a given language. It currently works with `yamlls` and `jsonls` and I was wondering if there was a way to integrate it with `taplo` as well. I've opened [an issue](https://github.com/b0o/SchemaStore.nvim/issues/25) to track this.

I've checked out the Rust docs and found [this](https://docs.rs/taplo-lsp/0.7.0/taplo_lsp/config/struct.LspConfig.html#structfield.schema) and [that](https://docs.rs/taplo-lsp/0.7.0/taplo_lsp/config/struct.SchemaConfig.html) but I'm not sure what I'm looking at, since I never written or even read Rust before.

As an example, here's how it integrates with `yamlls` and `jsonls`, I'd love to be able to do something like that with `taplo` (it's in Lua):

```lua
    jsonls = {
        settings = {
            json = {
                schemas = schemastore.json.schemas(),
                validate = { enable = true },
            },
        },
    },

    yamlls = {
        settings = {
            yaml = {
                schemaStore = {
                    -- You must disable built-in schemaStore support if you want to use
                    -- this plugin and its advanced options like `ignore`.
                    enable = false,
                    -- Avoid TypeError: Cannot read properties of undefined (reading 'length')
                    url = "",
                },
                schemas = schemastore.yaml.schemas(),
            },
        },
    },

```

I'd love some pointers!
Cheers :)

**Comment by ia0** [comment]
There should be nothing to configure. By default, taplo-lsp will use the schemastore catalog.

**Comment by zyriab** [comment]
That's neat :) thanks for the heads up!
