### ISSUE TITLE
semantic checks of toml files

### ISSUE THREAD

**Issue by tdyas** [tamasfe/taplo#563]
Are there any plans for "semantic" checks of TOML files to ensure that the files have specific value(s) for certain keys? (Or could this be supported with an existing feature somehow?)

For example, checking all `Cargo.toml` in a workspace to ensure they have `lints.worksapce` set to `true`.

**Comment by ia0** [comment]
No, Taplo is not meant for custom TOML parsing and processing. For that a crate like https://crates.io/crates/toml is adapted. Taplo provides TOML formatting and validation against schemas (by default those of JSON Schema Store).
