### ISSUE TITLE
In vscode, if the toml file path contains tasks, an error will be reported!

### ISSUE THREAD

**Issue by yuwenlong** [tamasfe/taplo#569]
@tamasfe 
In vscode, if the toml file path contains tasks, an error will be reported!

As shown in the figure.

![image](https://github.com/tamasfe/taplo/assets/11555324/0c1e8be2-1bed-4870-83e3-238892be0ba8)

**Comment by yuwenlong** [comment]
Still can't.
That's a problem. It hasn't been solved yet. Why is it closed?
Look at the first picture, it is very good to repeat the problem, you can try.

@JounQin @tamasfe 

![image](https://github.com/tamasfe/taplo/assets/11555324/fe5dc6a2-fc01-4959-aebf-2ec63a225e17)

**Comment by JounQin** [comment]
> That's a problem. It hasn't been solved yet. Why is it closed?

Because it is an intended behavior.

---

I pointed `[schema]`, you're setting `[[rule]]`

**Comment by yuwenlong** [comment]
Still can't. @JounQin 

![image](https://github.com/tamasfe/taplo/assets/11555324/67db4314-f80a-4b90-9069-0e88e7e20ace)
![image](https://github.com/tamasfe/taplo/assets/11555324/b2403678-d28c-4ede-a971-eb48c94d0e69)

**Comment by JounQin** [comment]
Can you please read the document more  carefully?

There is no `include` option for `schema` option, and you can use `enabled = false` to disable the schema.

**Comment by yuwenlong** [comment]
@JounQin 咱俩直接说中文吧，这样确实可以了，但路径包含 tasks 时，会报错的问题，后期会修复吗？

**Comment by JounQin** [comment]
这不是 bug ，而是路径匹配到了，自动使用对应的 schema，只是不符合你个人的使用预期。

**Comment by yuwenlong** [comment]
哦哦 了解了，谢谢
