### ISSUE TITLE
Properly handle oneOfs in schemas

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#57]
Currently all oneOfs are merged for autocompletion, instead only the relevant ones should be shown to the user.

**Comment by Bludator** [comment]
I think that this not only gives merged autocomplete result but also results in fails in validation:

[With this setup](https://www.jsonschemavalidator.net/s/0UY7KCWC)

VSCode extension:
```
Expected the value to be exactly one of "test1" or "test2", but it is valid for "test1" and "test2"
```
or CLI:
```
> npx @taplo/cli lint -s test-schema.json test.toml

npx: installed 20 in 5.21s
error: failed schema validation
 --> test.toml:1:1
  | 
1 | testProp = 10
  | ^ expected exactly one schema to match, but 2 schemas matched

failure: processed 1 document with 1 error
```

**Comment by tamasfe** [comment]
Yes, schemas probably need an overhaul along with #136 as well.
