### ISSUE TITLE
Open-VSX extension is outdated

### ISSUE THREAD

**Issue by benwaffle** [tamasfe/taplo#576]

**Comment by vnghia** [comment]
In the meantime, you can manually download the vsix from here https://marketplace.visualstudio.com/_apis/public/gallery/publishers/tamasfe/vsextensions/even-better-toml/0.19.2/vspackage

**Comment by panekj** [comment]
Related to #624

**Comment by panekj** [comment]
Even Better TOML 0.21.0 is now published on OpenVSX
