### ISSUE TITLE
doesn't work with poetry's package-mode = false

### ISSUE THREAD

**Issue by dimbleby** [tamasfe/taplo#577]
#558 was closed on the grounds that

> This is in poetry master so it's an upcoming change, not currently a problem.

poetry 1.8.0 was released ten days later

**Comment by panekj** [comment]
Validation schemas are hosted at [SchemaStore/schemastore](https://github.com/SchemaStore/schemastore) so it should be reported there, taplo is only a consumer of SchemaStore registry.

**Comment by dimbleby** [comment]
haha, thanks, that would have been a better reason for closing the other!
