### ISSUE TITLE
Schema repository

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#58]
Instead of bundling schemas, there should be some kind of repository where schemas could be stored, because every schema update right now requires a new release of all the tools.

**Comment by jasikpark** [comment]
Does this schema repository exist yet?

**Comment by jasikpark** [comment]
I'd like to contribute to adding more schemas, though I'm not sure where to start yet - I'd really like to see `netlify.toml` supported for example

**Comment by tamasfe** [comment]
@jasikpark much appreciated! Unfortunately I haven't progressed at all with this, I'm currently working on #61 whenever I have time, but it involves more changes than I initially thought.

If you'd like, you could have a stab at this issue, would help a lot.

The main idea is very basic, I'm thinking of a git repo (or a directory in this one) with all the schemas, and a server that periodically (or with hooks) creates an index (preferably in JSON format) and serves it.

The index should at least contain a last changed date for each schema and a direct link for download.

Also each schema should have its associations like currently we have in the extension, the index could probably contain these as well.

This application doesn't have to be in Rust, whatever is comfortable and simple. It might need to be able to handle git hooks and also get change dates for the files from git.

**Comment by jasikpark** [comment]
Sounds good! If I manage to, I'll have a go at that. I'd probably setup a static site generator that builds the index on site rebuild - and then it could run with a chron + githook rebuild - that's how I've got my personal site setup on netlify

**Comment by jasikpark** [comment]
https://github.com/SchemaStore/schemastore - https://schemastore.org looks nice - if only they also had toml in addition to json

**Comment by jasikpark** [comment]
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json -- looks like a good example for an index

**Comment by tamasfe** [comment]
I was thinking about it, but taplo relies too much on its extension schema property to provide useful info and alter behaviour.

I'm not against submitting schemas to schemastore.org, but they might not be useful for others.

Also that catalog is a bit restrictive, Taplo uses regex patterns instead of file names/extensions, and it also doesn't contain the last changed dates, so the clients don't know what schema they're missing (although this could be done with HTTP caching, it's still an unnecessary call).

**Comment by jasikpark** [comment]
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json -- looks like a good example for an index

**Comment by jasikpark** [comment]
Which doesn't include last changed dates? It looks like neither does atm, though I suppose currently the schemas for taplo are only meant to be compiled in to the tools, so the version management is via git commit?

**Comment by tamasfe** [comment]
> Which doesn't include last changed dates? It looks like neither does atm, though I suppose currently the schemas for taplo are only meant to be compiled in to the tools

The schemastore.org catalog has no date information in it for the individual schemas, which would be nice.

The point of this is issue so that they are not bundled with the tools but rather downloaded on demand, and I'd like them to be able to be cached on client-side in the extension and probably the CLI as well.

> so the version management is via git commit?
That is the plan, yes.

**Comment by jasikpark** [comment]
So moreso the promises made by https://unpkg.com/ - where a url shouldn't change what is hosted at it

**Comment by jasikpark** [comment]
I guess my question is whether the way that they deliver json schemas to vscode and jetbrains currently is not the right way to go? I'll maybe look at how updates work there?

**Comment by jasikpark** [comment]
https://www.schemastore.org/api/json/catalog.json it looks like the catalog includes a record of the versions of the schema, and includes "Last Updated" as an http header, which is probably the best way to setup caching for it

**Comment by tamasfe** [comment]
> it looks like the catalog includes a record of the versions of the schema

Yeah, that seems useful.

> and includes "Last Updated" as an http header, which is probably the best way to setup caching for it

Caching the catalog is one thing, and is way less important compared to caching the schemas themselves. If the dates in the catalog were available, the clients could simply compare them without making additional requests.

Anyway it is just a "nice to have", the main concern with schemastore.org is the lack of Taplo-specific metadata.

**Comment by jasikpark** [comment]
hmmmm ok - they also do seem to support yaml? i didn't know they were interchangeable-ish... https://github.com/SchemaStore/schemastore/pull/1155/files

What is the important Taplo-specific metadata? I might see if I make a separate repo that there's also a build that tries to upstream into schemastore w/o the taplo-specific metadata if that's what ends up happening

**Comment by tamasfe** [comment]
> What is the important Taplo-specific metadata? 

For now I can only think of the regex-based associations (instead of file names).

> upstream into schemastore w/o the taplo-specific metadata if that's what ends up happening

Sounds good, we could also use schemastore schemas in Taplo where applicable, although without customization and fewer features, but enough for some completions and validation.

**Comment by jasikpark** [comment]
https://github.com/SchemaStore/schemastore/issues/1394 - yeah they say just lazily update the schemas

**Comment by tamasfe** [comment]
> [SchemaStore/schemastore#1394](https://github.com/SchemaStore/schemastore/issues/1394) - yeah they say just lazily update the schemas

Yeah, I don't agree with it, but it is probably fine. If I were to create a repository, I'd include date information in the index, it's not a lot of effort, and makes things easier.

**Comment by jasikpark** [comment]
I can see the option for both - it seems like their solution is at least easier to make sure it's always up-to-date

**Comment by tamasfe** [comment]
> it seems like their solution is at least easier to make sure it's always up-to-date

The index is always updated on pushes, and the clients always fetch it whenever they think it is necessary.

It would be probably true if the schemas were stored externally, but we should have all the information about them in a git repo. Even if the schemas are stored somewhere else, it is better to poll them from the server and update the index than to leave it to the clients.

I can't think of any reason why storing the dates in the index wouldn't be worth it.

**Comment by jasikpark** [comment]
I believe that the index is manually updated rather than by tooling

**Comment by tamasfe** [comment]
I was very unhappy with the old website, so while I was rewriting it I also made a tool that publishes an index and all the schemas to github pages as well.

The client-side ended up being more work than I anticipated, and there is still some refactoring due, but this should be mostly done. The relevant docs can be found [here](https://taplo.tamasfe.dev/configuration/#schemas).

**Comment by jasikpark** [comment]
Looks great!
