### ISSUE TITLE
`tags` in samconfig.toml show error

### ISSUE THREAD

**Issue by mirumirumi** [tamasfe/taplo#581]
My samconfig.toml throws an error like this:

![image](https://github.com/tamasfe/taplo/assets/88871226/ed384945-b7ba-4c1a-b85e-749b5e90b0ad)

The AWS documentation says this is the correct way to write it:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

 The schema is set correctly.
![image](https://github.com/tamasfe/taplo/assets/88871226/f987a143-ce73-4a40-b5ab-bd4cf15f91be)

**Comment by JounQin** [comment]
https://raw.githubusercontent.com/aws/aws-sam-cli/master/schema/samcli.json

It's controlled by  https://www.schemastore.org/json/
