### ISSUE TITLE
Setting the indentation size in the even better toml extention

### ISSUE THREAD

**Issue by dorak88783** [tamasfe/taplo#582]
I might be very silly, but I can't find to change the indentation size in the even better toml plugin for vs code. I'm using on a code base with many repositories and they all use 4 spaces in their `pyproject.toml` files; running the extension will change it to 2 spaces. It's confusing to me where I should look for this setting: in the vs code extension, or in some taplo config file?

**Comment by JounQin** [comment]
https://taplo.tamasfe.dev/configuration/file.html#formatting-options

https://taplo.tamasfe.dev/configuration/formatter-options.html

Please read document carefully.

**Comment by dorak88783** [comment]
Thanks, I was indeed silly. I thought `indent_string` was a single char so I was looking for another field to specify the amount, but it clearly should be the full string, so 4 spaces in my case.

**Comment by JounQin** [comment]
Please provide an online but minimal runnable reproduce then.
