### ISSUE TITLE
Flags falsely on a googleAnalytics ID

### ISSUE THREAD

**Issue by digital-shokunin** [tamasfe/taplo#583]
Message:
"UA-37662566-1" does not match "(UA-\d{6}-\d)|(G-\w+)"Even Better TOML

My Google Anayltics ID is correct and I verified it in the portal. The rule/regex is invalid

**Comment by JounQin** [comment]
Any spec reference? And PR welcome.

**Comment by digital-shokunin** [comment]
Weirdly Google seems to be non-specific, I got that from querying various LLMs/searches. 

I was going to do a pull request but had trouble finding (even with a search) where that regex string is located.

**Comment by JounQin** [comment]
What file are you editing? Mostly you should PR to https://github.com/schemastore/schemastore
