### ISSUE TITLE
Links on "Binary Releases" documentation page do not work

### ISSUE THREAD

**Issue by NicksPatties** [tamasfe/taplo#588]
The links for both the default and full builds on the [Binary Releases](https://taplo.tamasfe.dev/cli/installation/binary.html) page are broken.

Here's an example of me trying to download talpo with `curl`.
```sh
$ curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz
curl: (22) The requested URL returned error: 404
```

**Comment by nikolay** [comment]
@tamasfe Any chance to fix the missing binaries as several package managers are failing now?

**Comment by rami3l** [comment]
@panekj Looks like https://github.com/tamasfe/taplo/issues/542 has been closed but the binaries are still not there in https://github.com/tamasfe/taplo/releases/tag/release-taplo-cli-0.9.0? I'm a bit confused now...

**Comment by panekj** [comment]
> I'm a bit confused now...

It's because the other "maintainer" did multiple things without consulting and then disappeared. I'm still working on fixing whole project, but it's a convoluted monorepo of multiple things depending on each other which makes it a bit hard to test and not break at the same time.

**Comment by panekj** [comment]
There are still few issues like taplo-cli not updated on crates.io but the GitHub release is now live: https://github.com/tamasfe/taplo/releases/tag/0.9.2
