### ISSUE TITLE
Feature Request: Add support for cargo-machete

### ISSUE THREAD

**Issue by Elrendio** [tamasfe/taplo#597]
Hello 👋

Thanks a lot for this awesome librairy and VSCode extension 😊

Would you be open to adding an integration with [`cargo machete`](https://github.com/bnjbvr/cargo-machete) to highlight unused dependencies in toml files?

**Downsides:**
- [`cargo machete`](https://github.com/bnjbvr/cargo-machete) is faillible and has known false positive that can't and won't be fixed. (EG dependencies only used in macros)
=> I think upside of compilation time of not compiling unused deps is worth it.
- It might slow down the execution of the extension
=> I think upside of compilation time of not compiling unused deps is worth it.
- This project is called `Even Better Toml` and not `Even Better Cargo.toml`, this integration might be too rust specifics.

**FAQ:**
- Why [`cargo machete`](https://github.com/bnjbvr/cargo-machete) and not [`cargo udeps`](https://github.com/est31/cargo-udeps)?
Speed :rocket: udeps requires compiling the crate which takes some time and can become cubersome when saving cargo.toml files.
- Why integrate it within `Even Better Toml` and not a custom extension?
Unused dependencies is very small problem and I'm not sure it would be worth the investment to create a extension just for that.
- Activate it by default or not?
I think it should be activated by default as developers might not be aware that rustc doesn't warn on unused dependencies (specially since it does so much other things)

**Comment by panekj** [comment]
Hello

> Would you be open to adding an integration with [`cargo machete`](https://github.com/bnjbvr/cargo-machete) to highlight unused dependencies in toml files?

In short, no. Long version, the project currently lacks active maintainers so there wouldn't be anything happening in terms of implementing this.
Another thing is, taplo is a schema linter, it auto-completes and provides highlight towards configuration issues based on the provided schema only.
Implementing separate tool would require re-working how taplo sources and presents information.

**Comment by panekj** [comment]
Closing since I think it's out of scope for the project
