### ISSUE TITLE
False positive syntax error when using dotted key syntax

### ISSUE THREAD

**Issue by msrd0** [tamasfe/taplo#601]
I recently learned that you can write `mydep.path = ...` instead of `mydep = { path = ... }`. However, this amazing extension unfortunately gives a false positive syntax error when using this syntax:

![Screenshot_2024-04-20-21-11-53](https://github.com/tamasfe/taplo/assets/7853372/212d5042-3da4-4aee-817f-5bd1f4c2c5ac)

This is the relevant toml snippet from my workspace `Cargo.toml`:

```toml
[workspace.dependencies]
mydep.path = "./mydep"
```

Given that cargo accepts my file, I assume it is valid toml and should not trigger syntax errors.

**Comment by panekj** [comment]
Extension isn't distinguishing valid values, it's all provided by file schema in which case it might have recognised file as something other than Cargo Manifest, you have outdated schema downloaded or there are local overrides in place.

**Comment by panekj** [comment]
I also can't reproduce this problem locally.
![image](https://github.com/tamasfe/taplo/assets/50457605/cb0e13fc-ea7c-48ce-b418-15d4a9a0b414)

**Comment by tamasfe** [comment]
The error is not coming from this extension, this repo is for the [Event Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) extension.

**Comment by msrd0** [comment]
Hm weird, I don't have any other toml extensions installed. But today the error is gone so I have no idea what the problem was. I didn't change any settings since yesterday :shrug:
