### ISSUE TITLE
Slow formatting when using @taplo/cli

### ISSUE THREAD

**Issue by tifandotme** [tamasfe/taplo#606]
I tried installing both using @taplo/cli through npm and taplo-cli through cargo.

I've noticed that when using the latter, formatting time is instantaneous compared to the JavaScript wrapper, which took around 1 second.

Would you care to explain why this is the case? 

Thank you for the amazing tool

**Comment by panekj** [comment]
> Would you care to explain why this is the case?

It's because taplo-cli is a native executable build for your host while @taplo/cli is a JS script that is roundtripping via NodeJS runtime and loading WASM build of taplo-cli, therefore you get the overhead of the runtime + WASM.
