### ISSUE TITLE
How is this VSCode extension aware of the right completions for my Alacritty TOML file? I see something incorrect

### ISSUE THREAD

**Issue by eduarddejong** [tamasfe/taplo#607]
First of all. Thanks for this amazing extension! It's really great.

Originally I installed it for my own Rust projects, but turns out it even recognizes the right things for the Alacritty terminal that I just installed on my Arch Linux system.

I 'm talking about a file called ~/.alacritty.toml in my user home dir.

What I noticed was the following:
the autocompletion wants me to write this:
```
[color.primary]
foreground = "#d8d8d8"
background = "#181818"
```

But Alacritty showed an error.
Turns out it needed to be ("colors" in plural):
```
[colors.primary]
foreground = "#d8d8d8"
background = "#181818"
```

But the autocompletion stops helping me here.
And this is true for the entire "colors" category.

Is the source for this issue inside this project or do I need to report it somewhere else?

Thanks in advance.

**Comment by panekj** [comment]
Validation is provided by schemas hosted in SchemaStore, which should be reported there or the upstream that maintains schema: https://github.com/SchemaStore/schemastore/blob/2c76ce21bee86de60ae150ef24a8ca4ed2a850fa/src/api/json/catalog.json#L5419

**Comment by eduarddejong** [comment]
Thanks! I have created an issue there.
