### ISSUE TITLE
Standalone LSP

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#61]
A standalone LSP is being worked on on the [feat-lsp](https://github.com/tamasfe/taplo/tree/feat-lsp) branch.
This should be able to work as a separate native executable as well as inside a NodeJS environment.

I also refactored `lsp-async-stub`, and removed `lsp-types` from taplo itself while I was at it.

Things remaining:
- [x] implement LSP via TCP, currently only stdio is used
- [x] update scripts and test it for VSCode to make sure nothing broke
- [x] handle client capabilities (because we don't know all the clients anymore) 
- [x] document additional LSP message methods, as all of them rely on VSCode

An example usage to test it could be: `python ./taplo-lsp/scripts/test_input.py | cargo run --bin taplo-lsp run`.

/cc @kkiyama117

**Comment by kkiyama117** [comment]
@tamasfe I appreciate for your kindness. I'll see what I can do with the new one.

**Comment by tamasfe** [comment]
Thanks! 

I had to spawn a thread for reading `stdin` so that it wouldn't keep tokio from shutting down. For the TCP implementation a simple async write to the socket like you did in your attempt should be enough.

Tokio currently doesn't seem to care about pending futures, so we have to make sure to block on all the required futures before shutting it down, such as [writing all the messages to stdout](https://github.com/tamasfe/taplo/blob/9d04ed8bc9a1fe940d1092c2a3fa613cff4941a3/taplo-lsp/bin/lsp.rs#L150).

**Comment by tamasfe** [comment]
Alright, I also implemented the TCP part, I'm not sure what the LSP spec says about this, but the server right now is supposed to live as long as the client, support multiple clients, and should shutdown after a lost connection.

Also there are some basic tests written in rust, so no external scripts are required just the good old cargo test.

**Comment by kkiyama117** [comment]
@tamasfe I understand. Now I'm on making vim extension with it, Thank you very much.
