### ISSUE TITLE
Complaining about cranelift (shouldn't do it)

### ISSUE THREAD

**Issue by amab8901** [tamasfe/taplo#610]
![image](https://github.com/tamasfe/taplo/assets/83634595/922615e4-d8a0-41b7-ba34-3b8aeb88ca1f)

I want to have cranelift in the components, but Even Better Toml complains about it, and I think it shouldn't do so. Why does it have to limit itself only to the specified list of components? Those aren't the only components that the Rust ecosystem offers.

**Comment by panekj** [comment]
We don't maintain schemas used to validate the files, please raise an issue in https://github.com/SchemaStore/schemastore if a schema is out of date.
