### ISSUE TITLE
taplo: error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by Conaclos** [tamasfe/taplo#616]
Taplo is used in one of the projects I am working on.
My Linux system uses OpenSSL 3.3.1

Since today, I got the following error:

```
taplo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

In `/usr/lib`, I have `libssl.so.3`.

I am not sure to understand why Taplo requires OpenSSL to format TOML files? Is there a way of disabling it? Thanks!

**Comment by panekj** [comment]
> I am not sure to understand why Taplo requires OpenSSL to format TOML files?

Because it doesn't format files only, it has much more functionality.

> Is there a way of disabling it?

Build it yourself or get your Linux distribution to add taplo to available packages
