### ISSUE TITLE
mypy pyproject.toml error: Additional properties are not allowed ('no_namespace_packages' was unexpected)

### ISSUE THREAD

**Issue by Don-Burns** [tamasfe/taplo#618]
I am using the [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) Vs Code extension and am getting an error in my [mypy config for "no namespace packages"](https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-no-namespace-packages)
![image](https://github.com/tamasfe/taplo/assets/56016914/c60ba243-8b70-4089-89a9-235eb89a484c)
The option is valid and I don't believe there is any issues with my configuration, as it behaves as expected.

# Package/Extension Versions
Even Better TOML VsCode Extension: v0.19.2
mypy: 1.10.0

# Minimal Reproduction
[mypy_test.zip](https://github.com/user-attachments/files/15772789/mypy_test.zip)
Project Structure:
```
.
├── pyproject.toml
└── src
    ├── main.py
    ├── namespace_pkg
    │   ├── mod.py
    │   └── py.typed
    └── normal_pkg
        ├── __init__.py
        ├── mod.py
        └── py.typed
```
MyPy when using the `no-namespace-packages` option will not auto import without an `__init__.py` file.
Useful when building packages, as missing init files will usually be found before even commiting/in CI.
If you test, with the attached project, you will see that the error will change when commenting out the option in pyproject.toml (test cmd `mypy .` when in root of project)
or that the error will resolve when the option is enabled by adding `src/namespace_pkg/__init__.py` as desired.

I am happy to contribute towards a fix, but I would need some guidance as I didn't see anywhere obvious where different tooling schemas appear to be defined.

**Comment by panekj** [comment]
This is an issue with JSON schema, it should be reported to SchemaStore
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/partial-mypy.json

**Comment by Don-Burns** [comment]
Ah, apologies, will ask over there then. Thank you!
