### ISSUE TITLE
False failure if asterisk is inside string

### ISSUE THREAD

**Issue by Yajo** [tamasfe/taplo#63]
Issue Type: <b>Bug</b>

This code is good, but it appears as bad: 
![imagen](https://user-images.githubusercontent.com/973709/100231470-f623d580-2f1e-11eb-9b15-cb24a57c3749.png)

Extension version: 0.9.3
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.9.8-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.48GB (0.49GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 1b07b1f6-f187-42fc-aa9e-516fd1a4c83e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by tamasfe** [comment]
The `authors` value is invalid according to the [docs](https://python-poetry.org/docs/pyproject/#authors).

**Comment by Yajo** [comment]
Oh sorry, I was thinking that this only was basic TOML linter, not Poetry-specific.

**Comment by Yajo** [comment]
Oh but line 16 is still a false failure, right?

**Comment by tamasfe** [comment]
> Oh but line 16 is still a false failure, right?

Yep, the version regex has to be fixed in the poetry schema, I will get to it at some point.
