### ISSUE TITLE
`Cargo.toml` schema missing some workspace keys

### ISSUE THREAD

**Issue by musjj** [tamasfe/taplo#638]
The [documentation](https://doc.rust-lang.org/cargo/reference/workspaces.html) mentions the following attributes:

> * `[workspace]` --- Defines a workspace.
>   * `resolver` --- Sets the dependency resolver to use.
>   * `members` --- Packages to include in the workspace.
>   * `exclude` --- Packages to exclude from the workspace.
>   * `default-members` --- Packages to operate on when a specific package wasn't selected.
>   * `package` --- Keys for inheriting in packages.
>   * `dependencies` --- Keys for inheriting in package dependencies.
>   * `lints` --- Keys for inheriting in package lints.
>   * `metadata` --- Extra settings for external tools.

But the current [schema](https://taplo.tamasfe.dev/schemas/Cargo.toml.json) only lists:

```json
"default-members": …,
"exclude": …,
"members": …,
"metadata": …,
"resolver" : …
```

**Comment by panekj** [comment]
The current schema is https://json.schemastore.org/cargo.json and any issues should for the schema should be created in https://github.com/schemastore/schemastore
