### ISSUE TITLE
VSCode extension publishing token expired (and OpenVSIX not uploaded)

### ISSUE THREAD

**Issue by echoix** [tamasfe/taplo#642]
I saw that there was supposed to be a release of the vscode extension, but the last couple version changes for https://github.com/tamasfe/taplo/commits/master/editors/vscode/package.json were never released.

For example, the last 0.20.2 release wasn't successful, and noted here: https://github.com/tamasfe/taplo/commit/4ba6c5325670db2ba4b3a7aa9619e84077317aca#commitcomment-144072575

Personally, I'm more interested in the OpenVSIX publishing, as I use it way more often through Gitpod.

Also, if the vsix could be uploaded as a artifact or release binary, at least we could use it.

On OpenVSIX, the last release is 0.19.1, and on the VS Marketplace, 0.19.2.

**Comment by panekj** [comment]
Thanks, already aware of the issue and I think opening more (GitHub) issues is not going to help.
