### ISSUE TITLE
pyproject.toml broken poetry with virtualenvs section

### ISSUE THREAD

**Issue by LewisCowlesMotive** [tamasfe/taplo#651]
Hi, thanks for authoring, this plugin was causing confusion for one of our devs
https://github.com/tamasfe/taplo/issues/460 touches on the same type of issue
config added to pyproject.toml by poetry, was being recommended to be moved to poetry.toml

I've just asked the dev to remove this plugin that none of the rest of us use if it's making unhelpful noise; but I thought I should also report here.

**Comment by abelcheung** [comment]
Apparently have been fixed in SchemaStore/schemastore#3616 and SchemaStore/schemastore#3709 quite a while ago.
