### ISSUE TITLE
Make binary releases on GitHub executable

### ISSUE THREAD

**Issue by Okeanos** [tamasfe/taplo#663]
I noticed a while ago that the binary releases here on GitHub are not executable by default:

```bash
TAPLO_VERSION="0.8.1"
TAPLO_SHASUM="e9c270c75172a33ebe3136c4190d414d93190ffe800fa1b10c1ac302fddd744a"
curl --fail --silent --show-error --location --output taplo.gz \
            https://github.com/tamasfe/taplo/releases/download/${TAPLO_VERSION}/taplo-full-linux-x86_64.gz
echo "${TAPLO_SHASUM} taplo.gz" | sha256sum --check
gunzip --decompress taplo.gz
stat -c%A taplo
```

Will result in

```output
-rw-r--r--
```

This happens regardless of architecture and operating system (and version) and is somewhat unexpected.

Would it be possible to make the binaries executable (`+x`) by default?

**Comment by panekj** [comment]
> Would it be possible to make the binaries executable (`+x`) by default?

No, as it would require to archive files in e.g. `tar`.
