### ISSUE TITLE
suppress parts of https://taplo.tamasfe.dev/schemas/Cargo.toml.json from other lsp

### ISSUE THREAD

**Issue by frederik-uni** [tamasfe/taplo#665]
I built a crate/version/feature suggestion language server. When I try to suggest the versions, I get the version suggestion, which I want to suppress. & when I am typing in the versionstring I get kinda useless suggestions I don't wanna see. Is there a way to disable it from another lsp?

<img width="821" alt="Screenshot 2024-08-30 at 12 40 40" src="https://github.com/user-attachments/assets/4733472a-61fb-4212-bd4c-b101f05507cd">
<img width="776" alt="Screenshot 2024-08-30 at 12 39 25" src="https://github.com/user-attachments/assets/b7c39b57-36e1-4196-9959-e751933f9a1d">

**Comment by panekj** [comment]
That would be up to your editor

**Comment by frederik-uni** [comment]
is there a way to overwrite the built in schemas?

**Comment by panekj** [comment]
There isn't a built-in schema, all schemas are sourced from SchemaStore. For overriding see https://taplo.tamasfe.dev/configuration/using-schemas.html
