### ISSUE TITLE
`cargo build --frozen` does not work

### ISSUE THREAD

**Issue by halostatue** [tamasfe/taplo#673]
I'm trying to create a [MacPorts](https://macports.org) portfile for taplo-cli and it fails to build with the standard build mechanism which uses `cargo build --release --frozen -v -j10`.

When `--frozen` is removed, several packages are updated in `Cargo.lock`.

I’m not *quite* sure what would be required to force `--frozen` to work (MacPorts also performs offline builds), but given some direction I am happy to provide a pull request. This is accurate as of the most recent tag v0.9.3.

```diff
diff --git i/Cargo.lock w/Cargo.lock
index 97c2b8d3a625..60e76f9a824f 100644
--- i/Cargo.lock
+++ w/Cargo.lock
@@ -1114,11 +1114,11 @@ dependencies = [
  "hashbrown 0.12.3",
 ]
 
 [[package]]
 name = "lsp-async-stub"
-version = "0.6.3"
+version = "0.6.4"
 dependencies = [
  "anyhow",
  "async-trait",
  "futures",
  "getrandom",
@@ -2163,11 +2163,11 @@ version = "1.0.1"
 source = "registry+https://github.com/rust-lang/crates.io-index"
 checksum = "55937e1799185b12863d447f42597ed69d9928686b8d88a1df17376a097d8369"
 
 [[package]]
 name = "taplo"
-version = "0.13.1"
+version = "0.13.2"
 dependencies = [
  "ahash 0.8.8",
  "arc-swap",
  "assert-json-diff",
  "criterion",
@@ -2188,11 +2188,11 @@ dependencies = [
  "tracing",
 ]
 
 [[package]]
 name = "taplo-cli"
-version = "0.9.2"
+version = "0.9.3"
 dependencies = [
  "ansi_term",
  "anyhow",
  "async-ctrlc",
  "atty",
@@ -2221,11 +2221,11 @@ dependencies = [
  "url",
 ]
 
 [[package]]
 name = "taplo-common"
-version = "0.5.1"
+version = "0.5.2"
 dependencies = [
  "ahash 0.8.8",
  "anyhow",
  "arc-swap",
  "async-recursion",
@@ -2259,11 +2259,11 @@ dependencies = [
  "url",
 ]
 
 [[package]]
 name = "taplo-lsp"
-version = "0.7.1"
+version = "0.7.2"
 dependencies = [
  "anyhow",
  "arc-swap",
  "either",
  "figment",
```

**Comment by panekj** [comment]
This is duplicate of https://github.com/tamasfe/taplo/issues/643

**Comment by halostatue** [comment]
It appears so. Should this be left open until a new release is made, because I can't really do non-tagged releases.

**Comment by panekj** [comment]
You can patch the lockfile for current tag, or use either of these commands which should do it for you:
- `cargo update -p taplo --offline`
- `cargo regenerate-lockfile --offline`

**Comment by halostatue** [comment]
That looks like it will work (there is a way of patching files before building).
