### ISSUE TITLE
Semver regexes are overly strict (and probably pointless)

### ISSUE THREAD

**Issue by thomcc** [tamasfe/taplo#68]
I have a Cargo.toml that causes the "Even Better Toml" VSCode extension to report an error, despite it being valid. 

The invalid area is something like:
```toml
[dependencies]
winit-20 = { version = ">= 0.20, <= 0.21", package = "winit", optional = true }
```

Apparently `">= 0.20, <= 0.21"` isn't parsed correctly by this behemoth: https://github.com/tamasfe/taplo/blob/6a40cf7e1329e3b15b972d215a1b4604ff3bb09e/taplo/schemas/Cargo.json#L1091

The fix for *this string* is easy enough, you're missing `<=` in the blocks where the comparisons are handled, but in general trying to parse this with a regex is... Well, very likely impossible.

Semver version reqs likely aren't a regular language. The grammar is something like https://github.com/steveklabnik/semver-parser/blob/master/src/semver.pest.

Notice that they get quite complicated. That is, `0.4 < 0.9, 1.x || >=2.1.0 || 3.8 - 5.2` is not only totally legal ([yes, really!](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1a44fc67fdf6f764b11390add9e16046)), but it doesn't show off the full set of features.

Anyway, I think the `SemVer` regex in your schema is also too strict. One example that parses as `semver::Version` that your regex rejects is `" 1.0.0 "` (cargo trims the whitespace).

So, I'd say just accept a string for these. Definitely for the version req, but probably for both of them. I don't think they buy you much anyway, If I had used an invalid version req, rust-analyzer would have told me pretty quickly as it would fail to parse the file. And if I'm not using a Rust IDE, then Cargo would tell me right away too. That is: The pain falsely marking an error isn't really worth the trouble (I've had to disable your extension because of this being too hard to ignore).

That said, another option would be to figure out a way to use the `semver` crate to verify them, which would be fool-proof, since it's the same parser cargo uses. IDK how hard that would be in your code (seems nontrivial), but again I'm not sure it's worth the trouble.

**Comment by tamasfe** [comment]
You are right, semver reqs are causing issues for #63 as well, and invalid versions are detected by tools that use the config anyway.

I would keep the regex for the versions themselves (because [these](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) exist), just allow leading and trailing white space.

> That said, another option would be to figure out a way to use the semver crate to verify them, which would be fool-proof, since it's the same parser cargo uses. IDK how hard that would be in your code (seems nontrivial), but again I'm not sure it's worth the trouble.

I'm planning Cargo-specific features such as dependency/feature completions, we could do these checks there without too much effort, but this won't happen anytime soon.

> I've had to disable your extension because of this being too hard to ignore

Maybe there should be a switch to disable schema validation only while keeping completion and other features on.

**Comment by Aloso** [comment]
One potential solution is to implement non-regular patterns, e.g.

```js
"evenBetterToml": {
    "pattern": ["<spaces><ranges><spaces>"],
    "patternRefs": {
        "spaces": [" <spaces>", ""],
        "logicalOr": ["<spaces>||<spaces>"],
        "ranges": ["<range><logicalOr><ranges>", "<range>"],
        // etc.
    }
}
```

It's a bit more verbose than [this grammar](https://github.com/steveklabnik/semver-parser/blob/master/src/semver.pest), but also easier to parse.

**Comment by tamasfe** [comment]
Actually, if we use the schema extension, we could just do something like
```json5
"evenBetterToml": {
  "rules": ["semverRequirement"]
}
```
and then use the `semver` crate to validate these.

I'm not sure if I want to go down this path, but it might be worth exploring.

**Comment by tamasfe** [comment]
I've removed the semver requirement regexps for now, before custom rules (such as semver) [verify#2](https://github.com/tamasfe/verify/issues/2) must be resolved.
