### ISSUE TITLE
Language server error: taplo

### ISSUE THREAD

**Issue by albas99** [tamasfe/taplo#691]
I'm using the Zed code editor and lately I've been seeing this error in my bottom panel anytime I open Zed `Language server error: taplo` and when I open it I see the following message 
```
Language server error: taplo

status error 403, response: "{\"message\":\"API rate limit exceeded for {my_ip_address}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
-- stderr--
```
My question is what does taplo does in my editor and why am I getting a rate limit error because of it?

**Comment by albas99** [comment]
Okay, I get that, but that still doesn't explain why I'm getting rate limit errors. Is it sending some kind of request to github from the backend that's causing the rate limiting?

**Comment by panekj** [comment]
A lot of schemas available from https://www.schemastore.org/ are hosted on GitHub which can trigger rate-limits

**Comment by panekj** [comment]
There is no way to provide token because taplo doesn't interact with GitHub explicitly.

**Comment by sylvainOL** [comment]
ok, so we basically have to wait for rate limiting to disappear.
Understood, thanks for quick reply
