### ISSUE TITLE
Support VS Code remote development with extensionKind

### ISSUE THREAD

**Issue by rfgamaral** [tamasfe/taplo#7]
Hi,

Can you please give proper support for VS Code remote development by setting the proper value for `extensionKind` in the extension `package.json` file?

I believe the correct option for your "Even Better TOML" is:

```json
{
  "extensionKind": ["workspace"]
}
```

But please read [this documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) first and test on your side.

Kind rergards.

**Comment by tamasfe** [comment]
Hi, thanks, I'll look into it soon.

**Comment by tamasfe** [comment]
@rfgamaral It should be working correctly as of 0.4.1.

**Comment by rfgamaral** [comment]
Thank you :)
