### ISSUE TITLE
JSON to TOML

### ISSUE THREAD

**Issue by pierredewilde** [tamasfe/taplo#70]
In VSCode extension Even Better TOML (v0.9.3),  TOML may be converted to JSON via `Command Palette...`

```
>TOML
TOML: Paste as JSON
TOML: Copy Selection as JSON
```
What about the reverse conversion (JSON to TOML) ?

```
TOML: Paste JSON as TOML
TOML: Copy JSON Selection as TOML
```

**Comment by tamasfe** [comment]
This wasn't implemented because the Taplo library doesn't support outputting TOML, but should be trivial with [toml-rs](https://github.com/alexcrichton/toml-rs), I'll include this in the next version.

**Comment by tamasfe** [comment]
Done in `v0.10.0`.
