### ISSUE TITLE
Publish musllinux wheels

### ISSUE THREAD

**Issue by sanmai-NL** [tamasfe/taplo#701]
I need a `musllinux_1_2_aarch64` wheel. More generally, people e.g., building Alpine Linux based container images, need `musllinux` wheels. On [PyPI: `taplo`](https://pypi.org/project/taplo/#files) no such wheels have been published.

**Comment by panekj** [comment]
Duplicate of https://github.com/tamasfe/taplo/issues/658

**Comment by sanmai-NL** [comment]
Alpine Linux doesn't correspond to musllinux per se, but it's good to go back to that issue.
