### ISSUE TITLE
`View repository` option in crate hover details

### ISSUE THREAD

**Issue by Caellian** [tamasfe/taplo#712]
If a downloaded crate has `repository` in `Crate.toml`, it would be very helpful to show that link in details shown when hovering over the crate version.

In 70% of cases when I click on `View crate` (which opens crates.io) I actually only open it in order to open the crate `repository`.

Additionally, `lib.rs` and `docs.rs` links for crates would be nice.

**Comment by panekj** [comment]
Taplo doesn't provide any integration with Cargo, only what schemas provide.

**Comment by Caellian** [comment]
How bad would it be if it parsed `cargo metadata` for the project to get this additional information in one go?

I'm not familiar with schemas. I glanced over the code that generates the popup but couldn't figure out where schema information is being pulled from. Assuming it's a VSCode thing.

**Comment by panekj** [comment]
> How bad would it be if it parsed `cargo metadata` for the project to get this additional information in one go for all dependencies?

Even Better TOML (and taplo) are not meant to provide cargo integration. There are other extensions and projects that provide such functionality.

**Comment by panekj** [comment]
Forgot to mention, you probably want to report that to https://github.com/filllabs/dependi which is the extension that shows information about crate/versions. (I'm guessing it's that since it was `crates` extension before that was part of extension pack in VSCode)
