### ISSUE TITLE
Poetry schema - `url` is not required for PyPI, `default` is deprecated

### ISSUE THREAD

**Issue by rafrafek** [tamasfe/taplo#713]
Hello,

I'm receiving this schema error in my `pyproject.toml` file:

```
"url" is a required property
```

for this section:

```toml
[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

The schema is being validated by the `Even Better TOML` extension.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/554f13b9-4b59-4c00-a5b2-898671ff7d5b" />

I think the schema should allow the url to be missing in case it's the default PyPI source. So this key should be optional in that specific case:

https://github.com/tamasfe/taplo/blob/a8bc571ee28775e7d5ad84c2ea87cf5b61ab42f5/site/site/public/schemas/pyproject.toml.json#L336

I think the `default` key is deprecated:

https://github.com/tamasfe/taplo/blob/a8bc571ee28775e7d5ad84c2ea87cf5b61ab42f5/site/site/public/schemas/pyproject.toml.json#L341

**Comment by rafrafek** [comment]
The `url` parameter:
> Omit the url when specifying PyPI explicitly. Because PyPI is internally configured with Poetry, the PyPI repository cannot be configured with a given URL. Remember, you can always use poetry check to ensure the validity of the pyproject.toml file.
https://python-poetry.org/docs/repositories/#primary-package-sources

The `default` parameter:
> Configuring a default package source is deprecated because it is the same as the topmost [primary source](https://python-poetry.org/docs/repositories/#primary-package-sources). Just configure a primary package source and put it first in the list of package sources.

**Comment by panekj** [comment]
Schemas are provided via https://schemastore.org and issues should be reported to https://github.com/SchemaStore/schemastore/issues

**Comment by rafrafek** [comment]
I think there is a difference between Schema store and Even Better TOML, in Schema store there is an `if` condition that looks if the `url` is needed::
https://github.com/SchemaStore/schemastore/blob/8d8f3e85feb5dea75502d6594a34665186bc401e/src/schemas/json/partial-poetry.json#L670

**Comment by panekj** [comment]
`Even Better TOML` uses SchemaStore so there can't be any difference.


> I think there is a difference between Schema store and Even Better TOML, in Schema store there is an `if` condition that checks if the `url` is needed

Might be because you have `name = "PyPI"` and comparison is case-sensitive

**Comment by panekj** [comment]
Sidenote: schema should probably have `enum: ["pypi"]` for `name` key so it provides autocomplete although it wouldn't fix copy-pasting code (or maybe it can be made case-insensitive, but I don't know, would need to refresh my memory on schemas).
