### ISSUE TITLE
Rename the "evenBetterToml" extension

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#72]
Something like `x-taplo` could be better as the current name only refers to the vscode extension, but schemas are not tied to it. Also it follows a more common extension naming pattern (at least found in OpenAPI).

This is a breaking change for existing schemas, so `evenBetterToml` should be deprecated and supported simultaneously for some time instead of being instantly removed.

**Comment by jasikpark** [comment]
I suppose this is important for doing #58?

**Comment by tamasfe** [comment]
It's not important at all, the `evenBetterToml` property will stay for a while for compatibility anyway.
