### ISSUE TITLE
Feature Request: Prettier plugin for toml

### ISSUE THREAD

**Issue by jasikpark** [tamasfe/taplo#73]
https://github.com/bd82/toml-tools/issues/39 

The current prettier plugin isn't able to be maintained, so it is going to be deprecated, but it'd be great if there was a way to integrate with prettier to add toml support?

**Comment by tamasfe** [comment]
I don't know about prettier, but Taplo is available as a JS library with formatting exposed. https://taplo.tamasfe.dev/lib/#javascript

**Comment by tamasfe** [comment]
I think currently this is out of the scope of this project and it already provides ways to use as a library or a standalone formatter.

I won't stop anyone writing a prettier integration though, and I'm happy to help if there are any questions.

**Comment by caass** [comment]
Hello! I'm interested in building a prettier plugin using Taplo, where should I look to see the JS code generation? I poked around briefly but couldn't find it :(

**Comment by tamasfe** [comment]
hi @caass sorry I forgot to reply.

I decided to drop WASM support and focus on other targets for the near future. I will update the WASM bindings at some point, but I don't know when (PR also welcome). You can use [@taplo/lib](https://www.npmjs.com/package/@taplo/lib) for the time being, it's an old version though.

**Comment by tamasfe** [comment]
After realizing that native builds won't be enough (e.g. for the vscode on the web), I actually bit the bullet during the weekend and went for restoring the WASM target.

The documentation on the website is not yet updated, but the code is short and mostly documented, it can be found [here](https://github.com/tamasfe/taplo/blob/master/js/lib/src/index.ts). The latest version is published on [npm](https://www.npmjs.com/package/@taplo/lib/v/0.4.0-alpha.2).

You can also pass in environment callbacks, which can be used to read configuration files (e.g. with formatting options), this is not yet documented, but an example can be found [here](https://github.com/tamasfe/taplo/blob/938618f9523de599ec064dfcd03c73b3a4b9d5fb/editors/vscode/src/server.ts#L18).

I don't know how prettier works, so tell me if there's anything missing that you need.

**Comment by jasikpark** [comment]
Prettier generally expects a parser and a printer function: one takes in documents and spits out an AST, and the latter takes in AST and spits out Prettier printing ast

So is there an option for returning an AST of the TOML from the wasm?

ex of this all working together w/ a wasm parser is https://github.com/withastro/prettier-plugin-astro

**Comment by tamasfe** [comment]
Ah, it looks like it uses a custom AST format. You will have to take the syntax tree returned by [`parse`](https://docs.rs/taplo/latest/taplo/parser/fn.parse.html), traverse it and build up an AST for prettier and then serialize that at the js boundary.

And vice versa if you also need taplo to format the prettier AST (but at this point why would you need prettier).

The WASM bindings are in a separate [crate](https://github.com/tamasfe/taplo/tree/master/crates/taplo-wasm), and the js packages that are set up to use it are [here](https://github.com/tamasfe/taplo/tree/master/js). I accept PRs if you wish to reuse the boilerplate ci/cd setup.
