### ISSUE TITLE
features and package version completion for Cargo.toml

### ISSUE THREAD

**Issue by GopherJ** [tamasfe/taplo#76]
Hi, is it possible to consider adding features completion and package version completion for Cargo.toml?  diagnostic is also possbile, they are all super useful

**Comment by GopherJ** [comment]
cargo-whatfeatures support detect features

**Comment by tamasfe** [comment]
This is planned, but probably not anytime soon.

I'd like to work on non-cargo specific features such as the standalone LSP, and proper handling of JSON schemas first.

It would also be worth looking into whether some kind of coordination is possible with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer).

**Comment by tamasfe** [comment]
This is implemented in the next version (#231).

**Comment by tamasfe** [comment]
Sorry, iirc it was briefly a feature but the implementation was very hacky and had all sorts of issues so it didn't make into a release.

I don't see this becoming a thing, it's a complex feature and nobody works actively on the project as it's only kept afloat by maintainers.
