### ISSUE TITLE
[js/vscode] No syntax highlighting whatsoever

### ISSUE THREAD

**Issue by aspenluxxxy** [tamasfe/taplo#78]
![image](https://user-images.githubusercontent.com/65794972/103110252-50df4880-4615-11eb-9ab5-4902e1cea7ab.png)

VSCode info:

 - Version: 1.52.1 (system setup)
 - Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
 - Date: 2020-12-16T16:34:46.910Z
 - Electron: 9.3.5
 - Chrome: 83.0.4103.122
 - Node.js: 12.14.1
 - V8: 8.3.110.13-electron.0
 - OS: Windows_NT x64 10.0.19042

Extension is version 0.9.3, however I couldn't find a previous working version either. Switching to a default VSC theme did not help, nor did disabling extensions like Bracket Pair Colorizer 2, crates, or rust-analyzer

No debug output from the extension

**Comment by tamasfe** [comment]
I suspect it's the theme you use, can you try a different one?

**Comment by tamasfe** [comment]
Can you share your vscode config JSON? (make sure to remove any sensitive data if there's any)

You could also try temporarily disabling all extensions apart from this one.

**Comment by aspenluxxxy** [comment]
Hm, it seems to be inconsistent between themes

# Default Dark+
![image](https://user-images.githubusercontent.com/65794972/103111120-7cfbc900-4617-11eb-8fe9-7a88a229fe3b.png)
# Solarized Dark
![image](https://user-images.githubusercontent.com/65794972/103111125-884ef480-4617-11eb-8485-c42ffe18b5e4.png)
# Community Material Theme
![image](https://user-images.githubusercontent.com/65794972/103111131-94d34d00-4617-11eb-8ff5-3abaaef52a7d.png)
# Monokai
![image](https://user-images.githubusercontent.com/65794972/103111133-9dc41e80-4617-11eb-9691-b3c532dbe83e.png)
# One Dark Pro
![image](https://user-images.githubusercontent.com/65794972/103111141-b03e5800-4617-11eb-83d1-265245b680ff.png)
# Palenight
![image](https://user-images.githubusercontent.com/65794972/103111147-bf250a80-4617-11eb-9221-442c6d0aad02.png)

**Comment by tamasfe** [comment]
It seems to be working as intended then, the keys use the `variable.key.toml` scope, this usually works great, but not when the variables are white in the theme.

I'm open to suggestions on using a different scope, or you can also override the color manually in your config.

**Comment by aspenluxxxy** [comment]
Alright
