### ISSUE TITLE
support trace level

### ISSUE THREAD

**Issue by GopherJ** [tamasfe/taplo#79]
https://github.com/tamasfe/taplo/blob/master/taplo-lsp/src/external/wasm32/mod.rs#L88

coc-toml uses taplo internally, but currently the logs are printed directly from taplo server, which produced trace like:

![image](https://user-images.githubusercontent.com/33961674/103138378-43d45f00-46d2-11eb-8c91-c063af2ad3f6.png)

it's hard to read and the client is not able to configure the log trace.

**Comment by GopherJ** [comment]
I'd really want to have it looking like:


![image](https://user-images.githubusercontent.com/33961674/103138414-bfcea700-46d2-11eb-8c63-8af1d5fd39ca.png)

for better understanding

**Comment by GopherJ** [comment]
or maybe the client should send the config to server

**Comment by tamasfe** [comment]
Hm, debug messages should be removed when compiled with `--release` completely, it's either a bug, or they use it in debug mode. I'll get in touch and see what I can do.

**Comment by GopherJ** [comment]
@tamasfe looks like you are right:)

![image](https://user-images.githubusercontent.com/33961674/103138995-efcc7900-46d7-11eb-98cc-dfa99bccb62a.png)

**Comment by kkiyama117** [comment]
@tamasfe This is probrem of `coc-toml`, which uses `taplo-lsp`, and @GopherJ have already resolved it. 
@tamasfe and @GopherJ Thank you so much.

**Comment by tamasfe** [comment]
I currently don't think I'd like to expose any kind of runtime logging options as there aren't a lot of logs anyway unless it's for debugging. So I think this issue could be closed, feel free to reopen it or create an another one if you still need this feature.
