### ISSUE TITLE
Global config location?

### ISSUE THREAD

**Issue by jasonhan-vassar** [tamasfe/taplo#81]
Hi, does the Taplo CLI support a global config location? From the docs, it appears it only searches the working directory and the root folder of a project. My suggestion is to use a configurable location with a flag or to search something like $HOME/.config/taplo. Thanks!

**Comment by tamasfe** [comment]
Hi,

The docs for the CLI are non-exhaustive, there should be a flag that sets the path to the config file, I believe it's `-c` or `--config`.

**Comment by jasonhan-vassar** [comment]
Ah okay, thank you!
