### ISSUE TITLE
content overflow on docs website

### ISSUE THREAD

**Issue by jasikpark** [tamasfe/taplo#82]
the table for the schemas overflows a bit on small phones like my iPhone SE

![image](https://user-images.githubusercontent.com/10626596/103228410-63e46800-48f6-11eb-8898-1d9d25903872.png)

**Comment by tamasfe** [comment]
Thanks, I made some changes to the site, so it should be better for smaller screens.

**Comment by jasikpark** [comment]
https://taplo.tamasfe.dev/configuration/#schemas got a couple more problems: 

![image](https://user-images.githubusercontent.com/10626596/103244002-34972080-4921-11eb-9b23-d9fc83bc453c.png)
overflow when table is opened. 
![image](https://user-images.githubusercontent.com/10626596/103244010-38c33e00-4921-11eb-9776-738f2c1a0443.png)
overflow when table is opened
![image](https://user-images.githubusercontent.com/10626596/103244013-3c56c500-4921-11eb-866c-e2c941edb49d.png)
overflow from `<code>` block that doesn't wrap. 

Thanks for the quick fix!

**Comment by tamasfe** [comment]
Ah, I'll have to add even smaller breakpoints.

**Comment by tamasfe** [comment]
Thank you, I switched to vitepress instead of a hand-rolled website and styling, so these issues should be handled better by that.
