### ISSUE TITLE
Defining a key multiple times should be invalid as per spec.

### ISSUE THREAD

**Issue by pjmp** [tamasfe/taplo#9]
This crate advertises as **TOML v1.0.0-rc.1** compliant and the [spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v1.0.0-rc.1.md) forbids defining a key multiple times however as of  v1.0.0-alpha.4, i can define multiple keys:

```rust
# taplo = "1.0.0-alpha.4"

const SOURCE: &str =
"ip = '127.0.0.1'
ip = 'xxx'

[secret]
github = 'github-xxxxxxxxxxxxxxxxx'
travis = 'travis-xxxxxxxxxxxxxxxxx'
azure = 'azure-xxxxxxxxxxxxxxxxx'";

let rect = taplo::parser::parse(SOURCE);

assert_eq!(rect.errors.len(), 1);
```

**Comment by tamasfe** [comment]
`parse` only parses the syntax, and thus only reports syntax errors. (e.g. missing `=`).

Other checks happen when a DOM is created, so a workflow should look like this:

```rust
    const SOURCE: &str =
    "ip = '127.0.0.1'
    ip = 'xxx'
    
    [secret]
    github = 'github-xxxxxxxxxxxxxxxxx'
    travis = 'travis-xxxxxxxxxxxxxxxxx'
    azure = 'azure-xxxxxxxxxxxxxxxxx'";
    
    let rect = crate::parser::parse(SOURCE);
    assert_eq!(rect.errors.len(), 0);

    let root = rect.into_dom();
    assert_eq!(root.errors().len(), 1);
```

I'll have to get to document the library eventually, so I'll keep this issue open as a reminder.

**Comment by tamasfe** [comment]
I've added documentation that covers this in 791e86d504105f6223fefc1077ae9b808477227a.
