### ISSUE TITLE
Support inline json schema

### ISSUE THREAD

**Issue by lnu** [tamasfe/taplo#95]
It would be nice to have inline json schema support like it's done in vscode-yaml:
`# yaml-language-server: $schema=<url>`

You would just had this at the top of your toml file to enable schema validation.

**Comment by tamasfe** [comment]
What is the exact use-case for this?

I intentionally avoid relying on comments inside TOML documents as tool configuration metadata doesn't belong in the data itself.

**Comment by lnu** [comment]
We publish a json schema in ohmpyposh to help people fill their config file. It was json at first but now the config can be done in yaml or tom. In vs code, intellisense is supported for yaml using the red hat extension with either a global schema def in the user settings file or inline with a comment a the top of the yaml file. It would be nice for our users to be able to have intellisens in vs code using an inline schema without having to define it in their user settings.

**Comment by tamasfe** [comment]
You can now do this by adding the following line to your file:

```toml
#:schema https://example.com/schema.json
```

Please note that the syntax might change in the future, it is tracked in #97.
