### ISSUE TITLE
Open-vsx extension is outdated

### ISSUE THREAD

**Issue by pm4rcin** [tamasfe/taplo#96]
Hi, [open-vsx](https://open-vsx.org/extension/tamasfe/even-better-toml) extension for vscodium is outdated. Could you update it?

**Comment by tamasfe** [comment]
Thanks, after [this issue](https://github.com/EclipseFdn/open-vsx.org/issues/427) is resolved, every release will be published there as well.

**Comment by tamasfe** [comment]
Version `0.12.0` should be published.

The page still shows the old one but the listing version is correct, so I suppose the page should be updated eventually as well.
