### ISSUE TITLE
VS doesn't associate toml files

### ISSUE THREAD

**Issue by LeonardoGentile** [tamasfe/taplo#99]
Hello, thanks for this!
I have a problem, but I'm not sure it's coming from vscode or this extension.
I've a file called `hello.toml` and every time I open it, it's opened as plain text.

I've added the following to my settings but didn't fix the problem:

```
"files.associations": {
    "*.toml ": "toml"
  },
```
Any idea how can I fix this?

**Comment by tamasfe** [comment]
Hi,

You could try starting vscode with no extensions, and then only enabling this one.
You could also try an another toml extension to see if they work. Also make sure that only one extension is enabled for toml (in theory it shouldn't be a problem, but they all define their own `toml` file type).
Lastly you could remove all settings to see if something interferes.

**Comment by tamasfe** [comment]
I'll close this as this doesn't seem to be a problem with taplo, feel free to create a new issue otherwise.
